from tkinter import *
from tkinter import ttk
import tkinter as tk 
import os



login=Tk() 
login.title("Login") 
login.geometry("300x300")
login.resizable(width=False, height=False)
usuario=StringVar() 
usuario_label=Label(login, text="Ingrese Usuario") 
usuario_label.pack() 
usuario_entry=Entry(login, width=30, show="*", textvariable=usuario)
usuario_entry.pack() 
password=StringVar()
password_label=Label(login, text="Ingrese Contraseña")
password_label.pack()
password_entry=Entry(login, width=30, show="*", textvariable=password)
password_entry.pack() 
def ingresar(): 
    if usuario_entry.get()=="ardidas" and password_entry.get()=="123456":
        login.title("Correcto") 
        arididas()
        login.deiconify
        login.iconify
        login.destroy
    elif usuario_entry.get()=="caleñito" and password_entry.get()=="123456":
        login.title("Correcto") 
        calenito()
        login.deiconify
        login.iconify
        login.destroy
    elif usuario_entry.get()=="agacher" and password_entry.get()=="123456":
        login.title("Correcto") 
        agacheR()
        login.deiconify
        login.iconify
        login.destroy
    elif usuario_entry.get()=="pasteles" and password_entry.get()=="123456":
        login.title("Correcto") 
        pasteles()
        login.deiconify
        login.iconify
        login.destroy
    elif usuario_entry.get()=="asados" and password_entry.get()=="123456":
        login.title("Correcto") 
        asados()
        login.deiconify
        login.iconify
        login.destroy
    elif usuario_entry.get()=="empanadas" and password_entry.get()=="123456":
        login.title("Correcto") 
        empanadas()
        login.deiconify
        login.iconify
        login.destroy
    elif usuario_entry.get()=="samsung" and password_entry.get()=="123456":
        login.title("Correcto") 
        samgung()
        login.deiconify
        login.iconify
        login.destroy
    elif usuario_entry.get()=="applepera" and password_entry.get()=="123456":
        login.title("Correcto") 
        applepera()
        login.deiconify
        login.iconify
        login.destroy
    elif usuario_entry.get()=="tecnicos" and password_entry.get()=="123456":
        login.title("Correcto") 
        tecnicos()
        login.deiconify
        login.iconify
        login.destroy
    else: 
        login.title("Incorrecto")

b1=Button(login, text="Ingresar", command=ingresar)
b1.pack()







def arididas(): 
    ardidas2=Toplevel()
    ardidas2.geometry("1400x1000")
    def almacenaArchivo(nombreFile, cadenaAlmacenar):
        print('Inicia Registro de Ventas')
        file=open(nombreFile,'a')
        file.write(cadenaAlmacenar)
        file.close()
        print('Finaliza Registro de venta')
        
    def validararchivo(nombreFile):
        if os.stat(nombreFile).st_size==0:
         cadenaEncabezado="NOMBRE | APELLIDO | FECHA | CODIGO | CELULAR | PRECIO | RECURSO | CANTIDAD \n"
         almacenaArchivo(nombreFile,cadenaEncabezado)

    def enviarelementos(): 
        arbol2.insert("", END, text="En Inventario", values=(ElementoA2.get(),cantidad2.get(), codig2.get(), tip.get()))
        ElementoA2.delete(0, END)
        cantidad2.delete(0, END)
        codig2.delete(0, END)
        tip.delete(0, END)

    def editarregistro():
        selected=trev.focus() 
        trev.item(selected, text="Vendido", values=(nombr.get(), apellid.get(), hor.get(), fech.get(), codig.get(), numCelula.get(), precio_entry.get(), cantida.get()))
        nombr.delete(0, END)
        apellid.delete(0, END)
        hor.delete(0, END)
        fech.delete(0, END)
        codig.delete(0, END)
        numCelula.delete(0, END)
        precio_entry.delete(0, END)
        cantida.delete(0, END)

    def editregistroelemento():
        selected2=arbol2.focus() 
        arbol2.item(selected2, text="En Inventario", values=(ElementoA2.get(), cantidad2.get(), codig2.get(), tip.get()))
        ElementoA2.delete(0, END)
        cantidad2.delete(0, END)
        codig2.delete(0, END)
        tip.delete(0, END)

    def seleccionado():
        nombr.delete(0, END)
        apellid.delete(0, END)
        hor.delete(0, END)
        fech.delete(0, END)
        codig.delete(0, END)
        numCelula.delete(0, END)
        precio_entry(0, END)
        cantida.delete(0, END)
        selected=trev.focus() 
        valr=trev.item(selected, "values")
        nombr.insert(0, valr[0])
        apellid.insert(0, valr[1])
        hor.insert(0, valr[2])
        fech.insert(0, valr[3])
        codig.insert(0, valr[4])
        numCelula.insert(0, valr[5])
        precio_entry.insert(0, valr[6])
        cantida.insert(0, valr[7])   

    def seleccionado2():
        ElementoA2.delete(0, END)
        cantidad2.delete(0, END)
        codig2.delete(0, END)
        tip.delete(0, END)
        selected2=arbol2.focus() 
        valr2=arbol2.item(selected2, "values")
        ElementoA2.insert(0, valr2[0])
        cantidad2.insert(0, valr2[1])
        codig2.insert(0,valr2[2])
        tip.insert(0, valr2[3])
        
    def borrarregistro():
        remover=trev.selection()[0]
        trev.delete(remover)

    def eliminarcasillas(): 
        nombr.delete(0, END)
        apellid.delete(0, END)
        hor.delete(0, END)
        fech.delete(0, END)
        codig.delete(0, END)
        numCelula.delete(0, END)
        precio_entry.delete(0, END)
        cantida.delete(0, END)

    def enviardatos(): 
        nombredata=nombre.get()
        apellidodata=apellido.get() 
        horadata=hora.get()
        fechadata=fecha.get() 
        codigodata=codigo.get() 
        numCelulardata=numCelular.get()
        cursodata=curso.get()
        preciodata=precio_entry.get()
        cantidaddata=cantidad.get()
        print(nombredata, apellidodata, horadata, fechadata, codigodata, numCelulardata, cursodata,  cantidaddata)
        cadenaRegistro = nombredata + '|' + apellidodata + '|' + fechadata + '|' + str(codigodata) + '|' + str(numCelulardata) + '|' + cursodata + '|' + str(preciodata) + '|'  + str(cantidaddata) +'\n'
        validararchivo("ventas.txt")
        almacenaArchivo("ventas.txt", cadenaRegistro)
        trev.insert("", END,  text="Activo", values=(nombr.get(), apellid.get(), hor.get(), fech.get(), codig.get(), numCelula.get(), precio_entry.get(), cantida.get()))
    #-----------------------Cuerpo del programa-----------------------------------------------
    #---------Defino algunas variables que usare en diferentes funciones----------------------
    nombre=StringVar()
    apellido=StringVar() 
    hora=StringVar() 
    fecha=StringVar()
    codigo=IntVar() 
    numCelular=IntVar() 
    curso=StringVar()  
    prec=DoubleVar() 
    Elemento1=StringVar()
    codigo2=IntVar() 
    cantidad=IntVar() 
    tipo=StringVar()
    cantidad2A=IntVar()
    #---------------Panel de pestañas----------------------------------------------
    panel=ttk.Notebook(ardidas2) 
    panel.pack(fill="both", expand="yes")   
    #Pestaña 1-------------------------------------------------------------------------------
    tab1=ttk.Frame(panel)
    panel.add(tab1, text="Ventas") 
    nombrA = Label(tab1, text="Nombres:").place(x=22, y=70)
    nombr = Entry(tab1, textvariable=nombre, width="40")
    nombr.place(x=22, y=100)
    apellidA=Label(tab1, text="Apellidos: ").place(x=22, y=130) 
    apellid=Entry(tab1, textvariable=apellido, width=40)
    apellid.place(x=22, y=160)
    horA=Label(tab1, text="Producto").place(x=22, y=190)
    hor=Entry(tab1, textvariable=hora, width="40")
    hor.place(x=22, y=220)
    fechA=Label(tab1, text="Fecha D/M/A: ").place(x=22, y=250) 
    fech=Entry(tab1, textvariable=fecha, width="40")
    fech.place(x=22, y=280)  
    codigA=Label(tab1, text="Código:").place(x=22, y=310)
    codig=Entry(tab1, textvariable=codigo, width="40")
    codig.place(x=22, y=340)
    numCelulaA=Label(tab1, text="Número celular: ").place(x=22, y=370)
    numCelula=Entry(tab1,textvariable=numCelular, width="40")
    numCelula.place(x=22, y=400)
    precio_label=Label(tab1, text="Precio: ").place(x=22, y=430)
    precio_entry=Entry(tab1, textvariable=prec, width="40")
    precio_entry.place(x=22, y=460)
    cantidaA=Label(tab1, text="Cantidad:").place(x=22, y=490)
    cantida=Entry(tab1, textvariable=cantidad, width="40")
    cantida.place(x=22, y=520)   
    #----------------Botones--------------------------------------------
    etiqueta=Label(tab1, text="Sección de registro de ventas").place(x=400, y=5)
    datost=Label(tab1, text="Para efectuar una venta y enviar los datos del cliente, clique el siguiente boton:").place(x=400, y=150)
    botonenviar=ttk.Button(tab1, text="Enviar datos de registro", command=enviardatos).place(x=400, y=100) 
    botonborrar=ttk.Button(tab1, text="Borrar un solo registro", command=borrarregistro).place(x=400, y=200)
    borrar1=Label(tab1, text="Para borrar un registro seleccione en la tabla inferior: La venta y presione el boton: Borrar un solo registro").place(x=400, y=250)
    editartext=Label(tab1,text="Para editar un registro seleccione: en la tabla inferior: La venta y presione el boton: Editar Registro, cuando halla cambiado los valores presione: Actualizar").place(x=400, y=300)
    acutalizar=ttk.Button(tab1, text="Actualizar edición", command=editarregistro ).place(x=400, y=350)
    borrarlabel=Label(tab1, text="Para limpiar los campos de entrada de texto pulse: Limpiar").place(x=400, y=400)
    botonlimpiar=ttk.Button(tab1, text="Limpiar", command=eliminarcasillas).place(x=400, y=450)
    labelusuario=Label(tab1, text="Tienda: " + usuario_entry.get(), font="Helvetica 20 bold", fg="red" ).place(x=700,  y=5)
    #Treeview--------------------
    trev=ttk.Treeview(tab1, columns=("col1", "col2", "col3", "col4", "col5", "col6", "col7", "col8"))
    trev.column("#0", width=150, anchor=CENTER)
    trev.heading("#0", text="Venta", anchor=CENTER)
    trev.column("col1", width=150, anchor=CENTER)
    trev.heading("col1", text="Nombre", anchor=CENTER)
    trev.column("col2", width=150, anchor=CENTER)
    trev.heading("col2", text="Apellido", anchor=CENTER)
    trev.column("col3", width=150, anchor=CENTER)
    trev.heading("col3", text="Producto", anchor=CENTER)
    trev.column("col4", width=150, anchor=CENTER)
    trev.heading("col4", text="Fecha", anchor=CENTER)
    trev.column("col5", width=150, anchor=CENTER)
    trev.heading("col5", text="Código", anchor=CENTER)
    trev.column("col6", width=150, anchor=CENTER)
    trev.heading("col6", text="Número Celular", anchor=CENTER)
    trev.column("col7", width=150, anchor=CENTER)
    trev.heading("col7", text="Precio", anchor=CENTER)
    trev.column("col8", width=150, anchor=CENTER)
    trev.heading("col8", text="Cantidad", anchor=CENTER)
    trev.place(y=700)

    #Pestaña 2 Inventario de recursos---------------------------------------------------------------------------------------------------------------------
    tab2=ttk.Frame(panel)
    ElementoA1 = Label(tab2, text="Nombre del elemento:").place(x=22, y=70)
    ElementoA2= Entry(tab2, textvariable=Elemento1, width="40")
    ElementoA2.place(x=22, y=100)
    cantidadA2=Label(tab2, text="Cantidad: ").place(x=22, y=130) 
    cantidad2=Entry(tab2, textvariable=cantidad2A, width=40)
    cantidad2.place(x=22, y=160) 
    codigA2=Label(tab2, text="Código/ID del elemento:").place(x=22, y=190)
    codig2=Entry(tab2, textvariable=codigo2, width="40")
    codig2.place(x=22, y=220)
    textotipo=Label(tab2, text="Precio").place(x=22, y=250)
    tip=Entry(tab2, textvariable=tipo, width="40")
    tip.place(x=22, y=280)
    botonenviar2=ttk.Button(tab2, text="Enviar Elementos", command=enviarelementos)
    botonenviar2.place(x=22, y=310)  
    botoneditar2=ttk.Button(tab2,text="Editar Registro", command=seleccionado2 ).place(x=22, y=340)
    editartext2=Label(tab2,text="Para editar unr egistre seleccione: en la tabla inferior: presione el boton: Editar Registro, cuando halla cambiado los valores presione: Actualizar").place(x=22, y=370)
    acutalizar2=ttk.Button(tab2, text="Actualizar edición", command=editregistroelemento)
    acutalizar2.place(x=22, y=400)
    #----------Botones-----------
    panel.add(tab2, text="Inventario de productos") 
    etiqueta2=Label(tab2, text="Sección para visualizar el inventario disponible: ").place(x=5, y=5) 
    #Treeview----------------------------------
    arbol2=ttk.Treeview(tab2, columns=("col1", "col2", "col3", "col4"))
    arbol2.column("#0", width=150, anchor=CENTER)
    arbol2.heading("#0", text="Listado Elementos", anchor=CENTER)
    arbol2.column("col1", width=150, anchor=CENTER)
    arbol2.heading("col1", text="Producto", anchor=CENTER)
    arbol2.column("col2", width=150, anchor=CENTER)
    arbol2.heading("col2", text="Cantidad", anchor=CENTER)
    arbol2.column("col3", width=150, anchor=CENTER)
    arbol2.heading("col3", text="Código:", anchor=CENTER)
    arbol2.column("col4", width=150, anchor=CENTER)
    arbol2.heading("col4", text="Precio", anchor=CENTER)
    arbol2.place(y=440) 
def calenito(): 
    calenito=Toplevel()
    calenito.geometry("1400x1000")
    def almacenaArchivo(nombreFile, cadenaAlmacenar):
        print('Inicia Registro de Ventas')
        file=open(nombreFile,'a')
        file.write(cadenaAlmacenar)
        file.close()
        print('Finaliza Registro de venta')
        
    def validararchivo(nombreFile):
        if os.stat(nombreFile).st_size==0:
         cadenaEncabezado="NOMBRE | APELLIDO | FECHA | CODIGO | CELULAR | PRECIO | RECURSO | CANTIDAD \n"
         almacenaArchivo(nombreFile,cadenaEncabezado)

    def enviarelementos(): 
        arbol2.insert("", END, text="En Inventario", values=(ElementoA2.get(),cantidad2.get(), codig2.get(), tip.get()))
        ElementoA2.delete(0, END)
        cantidad2.delete(0, END)
        codig2.delete(0, END)
        tip.delete(0, END)

    def editarregistro():
        selected=trev.focus() 
        trev.item(selected, text="Vendido", values=(nombr.get(), apellid.get(), hor.get(), fech.get(), codig.get(), numCelula.get(), precio_entry.get(), cantida.get()))
        nombr.delete(0, END)
        apellid.delete(0, END)
        hor.delete(0, END)
        fech.delete(0, END)
        codig.delete(0, END)
        numCelula.delete(0, END)
        precio_entry.delete(0, END)
        cantida.delete(0, END)

    def editregistroelemento():
        selected2=arbol2.focus() 
        arbol2.item(selected2, text="En Inventario", values=(ElementoA2.get(), cantidad2.get(), codig2.get(), tip.get()))
        ElementoA2.delete(0, END)
        cantidad2.delete(0, END)
        codig2.delete(0, END)
        tip.delete(0, END)

    def seleccionado():
        nombr.delete(0, END)
        apellid.delete(0, END)
        hor.delete(0, END)
        fech.delete(0, END)
        codig.delete(0, END)
        numCelula.delete(0, END)
        precio_entry(0, END)
        cantida.delete(0, END)
        selected=trev.focus() 
        valr=trev.item(selected, "values")
        nombr.insert(0, valr[0])
        apellid.insert(0, valr[1])
        hor.insert(0, valr[2])
        fech.insert(0, valr[3])
        codig.insert(0, valr[4])
        numCelula.insert(0, valr[5])
        precio_entry.insert(0, valr[6])
        cantida.insert(0, valr[7])   

    def seleccionado2():
        ElementoA2.delete(0, END)
        cantidad2.delete(0, END)
        codig2.delete(0, END)
        tip.delete(0, END)
        selected2=arbol2.focus() 
        valr2=arbol2.item(selected2, "values")
        ElementoA2.insert(0, valr2[0])
        cantidad2.insert(0, valr2[1])
        codig2.insert(0,valr2[2])
        tip.insert(0, valr2[3])
        
    def borrarregistro():
        remover=trev.selection()[0]
        trev.delete(remover)

    def eliminarcasillas(): 
        nombr.delete(0, END)
        apellid.delete(0, END)
        hor.delete(0, END)
        fech.delete(0, END)
        codig.delete(0, END)
        numCelula.delete(0, END)
        precio_entry.delete(0, END)
        cantida.delete(0, END)

    def enviardatos(): 
        nombredata=nombre.get()
        apellidodata=apellido.get() 
        horadata=hora.get()
        fechadata=fecha.get() 
        codigodata=codigo.get() 
        numCelulardata=numCelular.get()
        cursodata=curso.get()
        preciodata=precio_entry.get()
        cantidaddata=cantidad.get()
        print(nombredata, apellidodata, horadata, fechadata, codigodata, numCelulardata, cursodata,  cantidaddata)
        cadenaRegistro = nombredata + '|' + apellidodata + '|' + fechadata + '|' + str(codigodata) + '|' + str(numCelulardata) + '|' + cursodata + '|' + str(preciodata) + '|'  + str(cantidaddata) +'\n'
        validararchivo("ventas.txt")
        almacenaArchivo("ventas.txt", cadenaRegistro)
        trev.insert("", END,  text="Activo", values=(nombr.get(), apellid.get(), hor.get(), fech.get(), codig.get(), numCelula.get(), precio_entry.get(), cantida.get()))
    #-----------------------Cuerpo del programa-----------------------------------------------
    #---------Defino algunas variables que usare en diferentes funciones----------------------
    nombre=StringVar()
    apellido=StringVar() 
    hora=StringVar() 
    fecha=StringVar()
    codigo=IntVar() 
    numCelular=IntVar() 
    curso=StringVar()  
    prec=DoubleVar() 
    Elemento1=StringVar()
    codigo2=IntVar() 
    cantidad=IntVar() 
    tipo=StringVar()
    cantidad2A=IntVar()
    #---------------Panel de pestañas----------------------------------------------
    panel=ttk.Notebook(calenito) 
    panel.pack(fill="both", expand="yes")   
    #Pestaña 1-------------------------------------------------------------------------------
    tab1=ttk.Frame(panel)
    panel.add(tab1, text="Ventas") 
    nombrA = Label(tab1, text="Nombres:").place(x=22, y=70)
    nombr = Entry(tab1, textvariable=nombre, width="40")
    nombr.place(x=22, y=100)
    apellidA=Label(tab1, text="Apellidos: ").place(x=22, y=130) 
    apellid=Entry(tab1, textvariable=apellido, width=40)
    apellid.place(x=22, y=160)
    horA=Label(tab1, text="Producto").place(x=22, y=190)
    hor=Entry(tab1, textvariable=hora, width="40")
    hor.place(x=22, y=220)
    fechA=Label(tab1, text="Fecha D/M/A: ").place(x=22, y=250) 
    fech=Entry(tab1, textvariable=fecha, width="40")
    fech.place(x=22, y=280)  
    codigA=Label(tab1, text="Código:").place(x=22, y=310)
    codig=Entry(tab1, textvariable=codigo, width="40")
    codig.place(x=22, y=340)
    numCelulaA=Label(tab1, text="Número celular: ").place(x=22, y=370)
    numCelula=Entry(tab1,textvariable=numCelular, width="40")
    numCelula.place(x=22, y=400)
    precio_label=Label(tab1, text="Precio: ").place(x=22, y=430)
    precio_entry=Entry(tab1, textvariable=prec, width="40")
    precio_entry.place(x=22, y=460)
    cantidaA=Label(tab1, text="Cantidad:").place(x=22, y=490)
    cantida=Entry(tab1, textvariable=cantidad, width="40")
    cantida.place(x=22, y=520)   
    #----------------Botones--------------------------------------------
    etiqueta=Label(tab1, text="Sección de registro de ventas").place(x=400, y=5)
    datost=Label(tab1, text="Para efectuar una venta y enviar los datos del cliente, clique el siguiente boton:").place(x=400, y=150)
    botonenviar=ttk.Button(tab1, text="Enviar datos de registro", command=enviardatos).place(x=400, y=100) 
    botonborrar=ttk.Button(tab1, text="Borrar un solo registro", command=borrarregistro).place(x=400, y=200)
    borrar1=Label(tab1, text="Para borrar un registro seleccione en la tabla inferior: La venta y presione el boton: Borrar un solo registro").place(x=400, y=250)
    editartext=Label(tab1,text="Para editar un registro seleccione: en la tabla inferior: La venta y presione el boton: Editar Registro, cuando halla cambiado los valores presione: Actualizar").place(x=400, y=300)
    acutalizar=ttk.Button(tab1, text="Actualizar edición", command=editarregistro ).place(x=400, y=350)
    borrarlabel=Label(tab1, text="Para limpiar los campos de entrada de texto pulse: Limpiar").place(x=400, y=400)
    botonlimpiar=ttk.Button(tab1, text="Limpiar", command=eliminarcasillas).place(x=400, y=450)
    labelusuario=Label(tab1, text="Tienda: " + usuario_entry.get(), font="Helvetica 20 bold", fg="red" ).place(x=700,  y=5)
    #Treeview--------------------
    trev=ttk.Treeview(tab1, columns=("col1", "col2", "col3", "col4", "col5", "col6", "col7", "col8"))
    trev.column("#0", width=150, anchor=CENTER)
    trev.heading("#0", text="Venta", anchor=CENTER)
    trev.column("col1", width=150, anchor=CENTER)
    trev.heading("col1", text="Nombre", anchor=CENTER)
    trev.column("col2", width=150, anchor=CENTER)
    trev.heading("col2", text="Apellido", anchor=CENTER)
    trev.column("col3", width=150, anchor=CENTER)
    trev.heading("col3", text="Producto", anchor=CENTER)
    trev.column("col4", width=150, anchor=CENTER)
    trev.heading("col4", text="Fecha", anchor=CENTER)
    trev.column("col5", width=150, anchor=CENTER)
    trev.heading("col5", text="Código", anchor=CENTER)
    trev.column("col6", width=150, anchor=CENTER)
    trev.heading("col6", text="Número Celular", anchor=CENTER)
    trev.column("col7", width=150, anchor=CENTER)
    trev.heading("col7", text="Precio", anchor=CENTER)
    trev.column("col8", width=150, anchor=CENTER)
    trev.heading("col8", text="Cantidad", anchor=CENTER)
    trev.place(y=700)

    #Pestaña 2 Inventario de recursos---------------------------------------------------------------------------------------------------------------------
    tab2=ttk.Frame(panel)
    ElementoA1 = Label(tab2, text="Nombre del elemento:").place(x=22, y=70)
    ElementoA2= Entry(tab2, textvariable=Elemento1, width="40")
    ElementoA2.place(x=22, y=100)
    cantidadA2=Label(tab2, text="Cantidad: ").place(x=22, y=130) 
    cantidad2=Entry(tab2, textvariable=cantidad2A, width=40)
    cantidad2.place(x=22, y=160) 
    codigA2=Label(tab2, text="Código/ID del elemento:").place(x=22, y=190)
    codig2=Entry(tab2, textvariable=codigo2, width="40")
    codig2.place(x=22, y=220)
    textotipo=Label(tab2, text="Precio").place(x=22, y=250)
    tip=Entry(tab2, textvariable=tipo, width="40")
    tip.place(x=22, y=280)
    botonenviar2=ttk.Button(tab2, text="Enviar Elementos", command=enviarelementos)
    botonenviar2.place(x=22, y=310)  
    botoneditar2=ttk.Button(tab2,text="Editar Registro", command=seleccionado2 ).place(x=22, y=340)
    editartext2=Label(tab2,text="Para editar unr egistre seleccione: en la tabla inferior: presione el boton: Editar Registro, cuando halla cambiado los valores presione: Actualizar").place(x=22, y=370)
    acutalizar2=ttk.Button(tab2, text="Actualizar edición", command=editregistroelemento)
    acutalizar2.place(x=22, y=400)
    #----------Botones-----------
    panel.add(tab2, text="Inventario de productos") 
    etiqueta2=Label(tab2, text="Sección para visualizar el inventario disponible: ").place(x=5, y=5) 
    #Treeview----------------------------------
    arbol2=ttk.Treeview(tab2, columns=("col1", "col2", "col3", "col4"))
    arbol2.column("#0", width=150, anchor=CENTER)
    arbol2.heading("#0", text="Listado Elementos", anchor=CENTER)
    arbol2.column("col1", width=150, anchor=CENTER)
    arbol2.heading("col1", text="Producto", anchor=CENTER)
    arbol2.column("col2", width=150, anchor=CENTER)
    arbol2.heading("col2", text="Cantidad", anchor=CENTER)
    arbol2.column("col3", width=150, anchor=CENTER)
    arbol2.heading("col3", text="Código:", anchor=CENTER)
    arbol2.column("col4", width=150, anchor=CENTER)
    arbol2.heading("col4", text="Precio", anchor=CENTER)
    arbol2.place(y=440) 
    
def agacheR(): 
    agache=Toplevel()
    agache.geometry("1400x1000")
    def almacenaArchivo(nombreFile, cadenaAlmacenar):
        print('Inicia Registro de Ventas')
        file=open(nombreFile,'a')
        file.write(cadenaAlmacenar)
        file.close()
        print('Finaliza Registro de venta')
        
    def validararchivo(nombreFile):
        if os.stat(nombreFile).st_size==0:
         cadenaEncabezado="NOMBRE | APELLIDO | FECHA | CODIGO | CELULAR | PRECIO | RECURSO | CANTIDAD \n"
         almacenaArchivo(nombreFile,cadenaEncabezado)

    def enviarelementos(): 
        arbol2.insert("", END, text="En Inventario", values=(ElementoA2.get(),cantidad2.get(), codig2.get(), tip.get()))
        ElementoA2.delete(0, END)
        cantidad2.delete(0, END)
        codig2.delete(0, END)
        tip.delete(0, END)

    def editarregistro():
        selected=trev.focus() 
        trev.item(selected, text="Vendido", values=(nombr.get(), apellid.get(), hor.get(), fech.get(), codig.get(), numCelula.get(), precio_entry.get(), cantida.get()))
        nombr.delete(0, END)
        apellid.delete(0, END)
        hor.delete(0, END)
        fech.delete(0, END)
        codig.delete(0, END)
        numCelula.delete(0, END)
        precio_entry.delete(0, END)
        cantida.delete(0, END)

    def editregistroelemento():
        selected2=arbol2.focus() 
        arbol2.item(selected2, text="En Inventario", values=(ElementoA2.get(), cantidad2.get(), codig2.get(), tip.get()))
        ElementoA2.delete(0, END)
        cantidad2.delete(0, END)
        codig2.delete(0, END)
        tip.delete(0, END)

    def seleccionado():
        nombr.delete(0, END)
        apellid.delete(0, END)
        hor.delete(0, END)
        fech.delete(0, END)
        codig.delete(0, END)
        numCelula.delete(0, END)
        precio_entry(0, END)
        cantida.delete(0, END)
        selected=trev.focus() 
        valr=trev.item(selected, "values")
        nombr.insert(0, valr[0])
        apellid.insert(0, valr[1])
        hor.insert(0, valr[2])
        fech.insert(0, valr[3])
        codig.insert(0, valr[4])
        numCelula.insert(0, valr[5])
        precio_entry.insert(0, valr[6])
        cantida.insert(0, valr[7])   

    def seleccionado2():
        ElementoA2.delete(0, END)
        cantidad2.delete(0, END)
        codig2.delete(0, END)
        tip.delete(0, END)
        selected2=arbol2.focus() 
        valr2=arbol2.item(selected2, "values")
        ElementoA2.insert(0, valr2[0])
        cantidad2.insert(0, valr2[1])
        codig2.insert(0,valr2[2])
        tip.insert(0, valr2[3])
        
    def borrarregistro():
        remover=trev.selection()[0]
        trev.delete(remover)

    def eliminarcasillas(): 
        nombr.delete(0, END)
        apellid.delete(0, END)
        hor.delete(0, END)
        fech.delete(0, END)
        codig.delete(0, END)
        numCelula.delete(0, END)
        precio_entry.delete(0, END)
        cantida.delete(0, END)

    def enviardatos(): 
        nombredata=nombre.get()
        apellidodata=apellido.get() 
        horadata=hora.get()
        fechadata=fecha.get() 
        codigodata=codigo.get() 
        numCelulardata=numCelular.get()
        cursodata=curso.get()
        preciodata=precio_entry.get()
        cantidaddata=cantidad.get()
        print(nombredata, apellidodata, horadata, fechadata, codigodata, numCelulardata, cursodata,  cantidaddata)
        cadenaRegistro = nombredata + '|' + apellidodata + '|' + fechadata + '|' + str(codigodata) + '|' + str(numCelulardata) + '|' + cursodata + '|' + str(preciodata) + '|'  + str(cantidaddata) +'\n'
        validararchivo("ventas.txt")
        almacenaArchivo("ventas.txt", cadenaRegistro)
        trev.insert("", END,  text="Activo", values=(nombr.get(), apellid.get(), hor.get(), fech.get(), codig.get(), numCelula.get(), precio_entry.get(), cantida.get()))
    #-----------------------Cuerpo del programa-----------------------------------------------
    #---------Defino algunas variables que usare en diferentes funciones----------------------
    nombre=StringVar()
    apellido=StringVar() 
    hora=StringVar() 
    fecha=StringVar()
    codigo=IntVar() 
    numCelular=IntVar() 
    curso=StringVar()  
    prec=DoubleVar() 
    Elemento1=StringVar()
    codigo2=IntVar() 
    cantidad=IntVar() 
    tipo=StringVar()
    cantidad2A=IntVar()
    #---------------Panel de pestañas----------------------------------------------
    panel=ttk.Notebook(agache) 
    panel.pack(fill="both", expand="yes")   
    #Pestaña 1-------------------------------------------------------------------------------
    tab1=ttk.Frame(panel)
    panel.add(tab1, text="Ventas") 
    nombrA = Label(tab1, text="Nombres:").place(x=22, y=70)
    nombr = Entry(tab1, textvariable=nombre, width="40")
    nombr.place(x=22, y=100)
    apellidA=Label(tab1, text="Apellidos: ").place(x=22, y=130) 
    apellid=Entry(tab1, textvariable=apellido, width=40)
    apellid.place(x=22, y=160)
    horA=Label(tab1, text="Producto").place(x=22, y=190)
    hor=Entry(tab1, textvariable=hora, width="40")
    hor.place(x=22, y=220)
    fechA=Label(tab1, text="Fecha D/M/A: ").place(x=22, y=250) 
    fech=Entry(tab1, textvariable=fecha, width="40")
    fech.place(x=22, y=280)  
    codigA=Label(tab1, text="Código:").place(x=22, y=310)
    codig=Entry(tab1, textvariable=codigo, width="40")
    codig.place(x=22, y=340)
    numCelulaA=Label(tab1, text="Número celular: ").place(x=22, y=370)
    numCelula=Entry(tab1,textvariable=numCelular, width="40")
    numCelula.place(x=22, y=400)
    precio_label=Label(tab1, text="Precio: ").place(x=22, y=430)
    precio_entry=Entry(tab1, textvariable=prec, width="40")
    precio_entry.place(x=22, y=460)
    cantidaA=Label(tab1, text="Cantidad:").place(x=22, y=490)
    cantida=Entry(tab1, textvariable=cantidad, width="40")
    cantida.place(x=22, y=520)   
    #----------------Botones--------------------------------------------
    etiqueta=Label(tab1, text="Sección de registro de ventas").place(x=400, y=5)
    datost=Label(tab1, text="Para efectuar una venta y enviar los datos del cliente, clique el siguiente boton:").place(x=400, y=150)
    botonenviar=ttk.Button(tab1, text="Enviar datos de registro", command=enviardatos).place(x=400, y=100) 
    botonborrar=ttk.Button(tab1, text="Borrar un solo registro", command=borrarregistro).place(x=400, y=200)
    borrar1=Label(tab1, text="Para borrar un registro seleccione en la tabla inferior: La venta y presione el boton: Borrar un solo registro").place(x=400, y=250)
    editartext=Label(tab1,text="Para editar un registro seleccione: en la tabla inferior: La venta y presione el boton: Editar Registro, cuando halla cambiado los valores presione: Actualizar").place(x=400, y=300)
    acutalizar=ttk.Button(tab1, text="Actualizar edición", command=editarregistro ).place(x=400, y=350)
    borrarlabel=Label(tab1, text="Para limpiar los campos de entrada de texto pulse: Limpiar").place(x=400, y=400)
    botonlimpiar=ttk.Button(tab1, text="Limpiar", command=eliminarcasillas).place(x=400, y=450)
    labelusuario=Label(tab1, text="Tienda: " + usuario_entry.get(), font="Helvetica 20 bold", fg="red" ).place(x=700,  y=5)
    #Treeview--------------------
    trev=ttk.Treeview(tab1, columns=("col1", "col2", "col3", "col4", "col5", "col6", "col7", "col8"))
    trev.column("#0", width=150, anchor=CENTER)
    trev.heading("#0", text="Venta", anchor=CENTER)
    trev.column("col1", width=150, anchor=CENTER)
    trev.heading("col1", text="Nombre", anchor=CENTER)
    trev.column("col2", width=150, anchor=CENTER)
    trev.heading("col2", text="Apellido", anchor=CENTER)
    trev.column("col3", width=150, anchor=CENTER)
    trev.heading("col3", text="Producto", anchor=CENTER)
    trev.column("col4", width=150, anchor=CENTER)
    trev.heading("col4", text="Fecha", anchor=CENTER)
    trev.column("col5", width=150, anchor=CENTER)
    trev.heading("col5", text="Código", anchor=CENTER)
    trev.column("col6", width=150, anchor=CENTER)
    trev.heading("col6", text="Número Celular", anchor=CENTER)
    trev.column("col7", width=150, anchor=CENTER)
    trev.heading("col7", text="Precio", anchor=CENTER)
    trev.column("col8", width=150, anchor=CENTER)
    trev.heading("col8", text="Cantidad", anchor=CENTER)
    trev.place(y=700)

    #Pestaña 2 Inventario de recursos---------------------------------------------------------------------------------------------------------------------
    tab2=ttk.Frame(panel)
    ElementoA1 = Label(tab2, text="Nombre del elemento:").place(x=22, y=70)
    ElementoA2= Entry(tab2, textvariable=Elemento1, width="40")
    ElementoA2.place(x=22, y=100)
    cantidadA2=Label(tab2, text="Cantidad: ").place(x=22, y=130) 
    cantidad2=Entry(tab2, textvariable=cantidad2A, width=40)
    cantidad2.place(x=22, y=160) 
    codigA2=Label(tab2, text="Código/ID del elemento:").place(x=22, y=190)
    codig2=Entry(tab2, textvariable=codigo2, width="40")
    codig2.place(x=22, y=220)
    textotipo=Label(tab2, text="Precio").place(x=22, y=250)
    tip=Entry(tab2, textvariable=tipo, width="40")
    tip.place(x=22, y=280)
    botonenviar2=ttk.Button(tab2, text="Enviar Elementos", command=enviarelementos)
    botonenviar2.place(x=22, y=310)  
    botoneditar2=ttk.Button(tab2,text="Editar Registro", command=seleccionado2 ).place(x=22, y=340)
    editartext2=Label(tab2,text="Para editar unr egistre seleccione: en la tabla inferior: presione el boton: Editar Registro, cuando halla cambiado los valores presione: Actualizar").place(x=22, y=370)
    acutalizar2=ttk.Button(tab2, text="Actualizar edición", command=editregistroelemento)
    acutalizar2.place(x=22, y=400)
    #----------Botones-----------
    panel.add(tab2, text="Inventario de productos") 
    etiqueta2=Label(tab2, text="Sección para visualizar el inventario disponible: ").place(x=5, y=5) 
    #Treeview----------------------------------
    arbol2=ttk.Treeview(tab2, columns=("col1", "col2", "col3", "col4"))
    arbol2.column("#0", width=150, anchor=CENTER)
    arbol2.heading("#0", text="Listado Elementos", anchor=CENTER)
    arbol2.column("col1", width=150, anchor=CENTER)
    arbol2.heading("col1", text="Producto", anchor=CENTER)
    arbol2.column("col2", width=150, anchor=CENTER)
    arbol2.heading("col2", text="Cantidad", anchor=CENTER)
    arbol2.column("col3", width=150, anchor=CENTER)
    arbol2.heading("col3", text="Código:", anchor=CENTER)
    arbol2.column("col4", width=150, anchor=CENTER)
    arbol2.heading("col4", text="Precio", anchor=CENTER)
    arbol2.place(y=440)  
def pasteles(): 
    pastel=Toplevel()
    pastel.geometry("1400x1000")
    def almacenaArchivo(nombreFile, cadenaAlmacenar):
        print('Inicia Registro de Ventas')
        file=open(nombreFile,'a')
        file.write(cadenaAlmacenar)
        file.close()
        print('Finaliza Registro de venta')
        
    def validararchivo(nombreFile):
        if os.stat(nombreFile).st_size==0:
         cadenaEncabezado="NOMBRE | APELLIDO | FECHA | CODIGO | CELULAR | PRECIO | RECURSO | CANTIDAD \n"
         almacenaArchivo(nombreFile,cadenaEncabezado)

    def enviarelementos(): 
        arbol2.insert("", END, text="En Inventario", values=(ElementoA2.get(),cantidad2.get(), codig2.get(), tip.get()))
        ElementoA2.delete(0, END)
        cantidad2.delete(0, END)
        codig2.delete(0, END)
        tip.delete(0, END)

    def editarregistro():
        selected=trev.focus() 
        trev.item(selected, text="Vendido", values=(nombr.get(), apellid.get(), hor.get(), fech.get(), codig.get(), numCelula.get(), precio_entry.get(), cantida.get()))
        nombr.delete(0, END)
        apellid.delete(0, END)
        hor.delete(0, END)
        fech.delete(0, END)
        codig.delete(0, END)
        numCelula.delete(0, END)
        precio_entry.delete(0, END)
        cantida.delete(0, END)

    def editregistroelemento():
        selected2=arbol2.focus() 
        arbol2.item(selected2, text="En Inventario", values=(ElementoA2.get(), cantidad2.get(), codig2.get(), tip.get()))
        ElementoA2.delete(0, END)
        cantidad2.delete(0, END)
        codig2.delete(0, END)
        tip.delete(0, END)

    def seleccionado():
        nombr.delete(0, END)
        apellid.delete(0, END)
        hor.delete(0, END)
        fech.delete(0, END)
        codig.delete(0, END)
        numCelula.delete(0, END)
        precio_entry(0, END)
        cantida.delete(0, END)
        selected=trev.focus() 
        valr=trev.item(selected, "values")
        nombr.insert(0, valr[0])
        apellid.insert(0, valr[1])
        hor.insert(0, valr[2])
        fech.insert(0, valr[3])
        codig.insert(0, valr[4])
        numCelula.insert(0, valr[5])
        precio_entry.insert(0, valr[6])
        cantida.insert(0, valr[7])   

    def seleccionado2():
        ElementoA2.delete(0, END)
        cantidad2.delete(0, END)
        codig2.delete(0, END)
        tip.delete(0, END)
        selected2=arbol2.focus() 
        valr2=arbol2.item(selected2, "values")
        ElementoA2.insert(0, valr2[0])
        cantidad2.insert(0, valr2[1])
        codig2.insert(0,valr2[2])
        tip.insert(0, valr2[3])
        
    def borrarregistro():
        remover=trev.selection()[0]
        trev.delete(remover)

    def eliminarcasillas(): 
        nombr.delete(0, END)
        apellid.delete(0, END)
        hor.delete(0, END)
        fech.delete(0, END)
        codig.delete(0, END)
        numCelula.delete(0, END)
        precio_entry.delete(0, END)
        cantida.delete(0, END)

    def enviardatos(): 
        nombredata=nombre.get()
        apellidodata=apellido.get() 
        horadata=hora.get()
        fechadata=fecha.get() 
        codigodata=codigo.get() 
        numCelulardata=numCelular.get()
        cursodata=curso.get()
        preciodata=precio_entry.get()
        cantidaddata=cantidad.get()
        print(nombredata, apellidodata, horadata, fechadata, codigodata, numCelulardata, cursodata,  cantidaddata)
        cadenaRegistro = nombredata + '|' + apellidodata + '|' + fechadata + '|' + str(codigodata) + '|' + str(numCelulardata) + '|' + cursodata + '|' + str(preciodata) + '|'  + str(cantidaddata) +'\n'
        validararchivo("ventas.txt")
        almacenaArchivo("ventas.txt", cadenaRegistro)
        trev.insert("", END,  text="Activo", values=(nombr.get(), apellid.get(), hor.get(), fech.get(), codig.get(), numCelula.get(), precio_entry.get(), cantida.get()))
    #-----------------------Cuerpo del programa-----------------------------------------------
    #---------Defino algunas variables que usare en diferentes funciones----------------------
    nombre=StringVar()
    apellido=StringVar() 
    hora=StringVar() 
    fecha=StringVar()
    codigo=IntVar() 
    numCelular=IntVar() 
    curso=StringVar()  
    prec=DoubleVar() 
    Elemento1=StringVar()
    codigo2=IntVar() 
    cantidad=IntVar() 
    tipo=StringVar()
    cantidad2A=IntVar()
    #---------------Panel de pestañas----------------------------------------------
    panel=ttk.Notebook(pastel) 
    panel.pack(fill="both", expand="yes")   
    #Pestaña 1-------------------------------------------------------------------------------
    tab1=ttk.Frame(panel)
    panel.add(tab1, text="Ventas") 
    nombrA = Label(tab1, text="Nombres:").place(x=22, y=70)
    nombr = Entry(tab1, textvariable=nombre, width="40")
    nombr.place(x=22, y=100)
    apellidA=Label(tab1, text="Apellidos: ").place(x=22, y=130) 
    apellid=Entry(tab1, textvariable=apellido, width=40)
    apellid.place(x=22, y=160)
    horA=Label(tab1, text="Producto").place(x=22, y=190)
    hor=Entry(tab1, textvariable=hora, width="40")
    hor.place(x=22, y=220)
    fechA=Label(tab1, text="Fecha D/M/A: ").place(x=22, y=250) 
    fech=Entry(tab1, textvariable=fecha, width="40")
    fech.place(x=22, y=280)  
    codigA=Label(tab1, text="Código:").place(x=22, y=310)
    codig=Entry(tab1, textvariable=codigo, width="40")
    codig.place(x=22, y=340)
    numCelulaA=Label(tab1, text="Número celular: ").place(x=22, y=370)
    numCelula=Entry(tab1,textvariable=numCelular, width="40")
    numCelula.place(x=22, y=400)
    precio_label=Label(tab1, text="Precio: ").place(x=22, y=430)
    precio_entry=Entry(tab1, textvariable=prec, width="40")
    precio_entry.place(x=22, y=460)
    cantidaA=Label(tab1, text="Cantidad:").place(x=22, y=490)
    cantida=Entry(tab1, textvariable=cantidad, width="40")
    cantida.place(x=22, y=520)   
    #----------------Botones--------------------------------------------
    etiqueta=Label(tab1, text="Sección de registro de ventas").place(x=400, y=5)
    datost=Label(tab1, text="Para efectuar una venta y enviar los datos del cliente, clique el siguiente boton:").place(x=400, y=150)
    botonenviar=ttk.Button(tab1, text="Enviar datos de registro", command=enviardatos).place(x=400, y=100) 
    botonborrar=ttk.Button(tab1, text="Borrar un solo registro", command=borrarregistro).place(x=400, y=200)
    borrar1=Label(tab1, text="Para borrar un registro seleccione en la tabla inferior: La venta y presione el boton: Borrar un solo registro").place(x=400, y=250)
    editartext=Label(tab1,text="Para editar un registro seleccione: en la tabla inferior: La venta y presione el boton: Editar Registro, cuando halla cambiado los valores presione: Actualizar").place(x=400, y=300)
    acutalizar=ttk.Button(tab1, text="Actualizar edición", command=editarregistro ).place(x=400, y=350)
    borrarlabel=Label(tab1, text="Para limpiar los campos de entrada de texto pulse: Limpiar").place(x=400, y=400)
    botonlimpiar=ttk.Button(tab1, text="Limpiar", command=eliminarcasillas).place(x=400, y=450)
    labelusuario=Label(tab1, text="Tienda: " + usuario_entry.get(), font="Helvetica 20 bold", fg="red" ).place(x=700,  y=5)
    #Treeview--------------------
    trev=ttk.Treeview(tab1, columns=("col1", "col2", "col3", "col4", "col5", "col6", "col7", "col8"))
    trev.column("#0", width=150, anchor=CENTER)
    trev.heading("#0", text="Venta", anchor=CENTER)
    trev.column("col1", width=150, anchor=CENTER)
    trev.heading("col1", text="Nombre", anchor=CENTER)
    trev.column("col2", width=150, anchor=CENTER)
    trev.heading("col2", text="Apellido", anchor=CENTER)
    trev.column("col3", width=150, anchor=CENTER)
    trev.heading("col3", text="Producto", anchor=CENTER)
    trev.column("col4", width=150, anchor=CENTER)
    trev.heading("col4", text="Fecha", anchor=CENTER)
    trev.column("col5", width=150, anchor=CENTER)
    trev.heading("col5", text="Código", anchor=CENTER)
    trev.column("col6", width=150, anchor=CENTER)
    trev.heading("col6", text="Número Celular", anchor=CENTER)
    trev.column("col7", width=150, anchor=CENTER)
    trev.heading("col7", text="Precio", anchor=CENTER)
    trev.column("col8", width=150, anchor=CENTER)
    trev.heading("col8", text="Cantidad", anchor=CENTER)
    trev.place(y=700)

    #Pestaña 2 Inventario de recursos---------------------------------------------------------------------------------------------------------------------
    tab2=ttk.Frame(panel)
    ElementoA1 = Label(tab2, text="Nombre del elemento:").place(x=22, y=70)
    ElementoA2= Entry(tab2, textvariable=Elemento1, width="40")
    ElementoA2.place(x=22, y=100)
    cantidadA2=Label(tab2, text="Cantidad: ").place(x=22, y=130) 
    cantidad2=Entry(tab2, textvariable=cantidad2A, width=40)
    cantidad2.place(x=22, y=160) 
    codigA2=Label(tab2, text="Código/ID del elemento:").place(x=22, y=190)
    codig2=Entry(tab2, textvariable=codigo2, width="40")
    codig2.place(x=22, y=220)
    textotipo=Label(tab2, text="Precio").place(x=22, y=250)
    tip=Entry(tab2, textvariable=tipo, width="40")
    tip.place(x=22, y=280)
    botonenviar2=ttk.Button(tab2, text="Enviar Elementos", command=enviarelementos)
    botonenviar2.place(x=22, y=310)  
    botoneditar2=ttk.Button(tab2,text="Editar Registro", command=seleccionado2 ).place(x=22, y=340)
    editartext2=Label(tab2,text="Para editar unr egistre seleccione: en la tabla inferior: presione el boton: Editar Registro, cuando halla cambiado los valores presione: Actualizar").place(x=22, y=370)
    acutalizar2=ttk.Button(tab2, text="Actualizar edición", command=editregistroelemento)
    acutalizar2.place(x=22, y=400)
    #----------Botones-----------
    panel.add(tab2, text="Inventario de productos") 
    etiqueta2=Label(tab2, text="Sección para visualizar el inventario disponible: ").place(x=5, y=5) 
    #Treeview----------------------------------
    arbol2=ttk.Treeview(tab2, columns=("col1", "col2", "col3", "col4"))
    arbol2.column("#0", width=150, anchor=CENTER)
    arbol2.heading("#0", text="Listado Elementos", anchor=CENTER)
    arbol2.column("col1", width=150, anchor=CENTER)
    arbol2.heading("col1", text="Producto", anchor=CENTER)
    arbol2.column("col2", width=150, anchor=CENTER)
    arbol2.heading("col2", text="Cantidad", anchor=CENTER)
    arbol2.column("col3", width=150, anchor=CENTER)
    arbol2.heading("col3", text="Código:", anchor=CENTER)
    arbol2.column("col4", width=150, anchor=CENTER)
    arbol2.heading("col4", text="Precio", anchor=CENTER)
    arbol2.place(y=440) 
def asados(): 
    asados=Toplevel()
    asados.geometry("1400x1000")
    def almacenaArchivo(nombreFile, cadenaAlmacenar):
        print('Inicia Registro de Ventas')
        file=open(nombreFile,'a')
        file.write(cadenaAlmacenar)
        file.close()
        print('Finaliza Registro de venta')
        
    def validararchivo(nombreFile):
        if os.stat(nombreFile).st_size==0:
         cadenaEncabezado="NOMBRE | APELLIDO | FECHA | CODIGO | CELULAR | PRECIO | RECURSO | CANTIDAD \n"
         almacenaArchivo(nombreFile,cadenaEncabezado)

    def enviarelementos(): 
        arbol2.insert("", END, text="En Inventario", values=(ElementoA2.get(),cantidad2.get(), codig2.get(), tip.get()))
        ElementoA2.delete(0, END)
        cantidad2.delete(0, END)
        codig2.delete(0, END)
        tip.delete(0, END)

    def editarregistro():
        selected=trev.focus() 
        trev.item(selected, text="Vendido", values=(nombr.get(), apellid.get(), hor.get(), fech.get(), codig.get(), numCelula.get(), precio_entry.get(), cantida.get()))
        nombr.delete(0, END)
        apellid.delete(0, END)
        hor.delete(0, END)
        fech.delete(0, END)
        codig.delete(0, END)
        numCelula.delete(0, END)
        precio_entry.delete(0, END)
        cantida.delete(0, END)

    def editregistroelemento():
        selected2=arbol2.focus() 
        arbol2.item(selected2, text="En Inventario", values=(ElementoA2.get(), cantidad2.get(), codig2.get(), tip.get()))
        ElementoA2.delete(0, END)
        cantidad2.delete(0, END)
        codig2.delete(0, END)
        tip.delete(0, END)

    def seleccionado():
        nombr.delete(0, END)
        apellid.delete(0, END)
        hor.delete(0, END)
        fech.delete(0, END)
        codig.delete(0, END)
        numCelula.delete(0, END)
        precio_entry(0, END)
        cantida.delete(0, END)
        selected=trev.focus() 
        valr=trev.item(selected, "values")
        nombr.insert(0, valr[0])
        apellid.insert(0, valr[1])
        hor.insert(0, valr[2])
        fech.insert(0, valr[3])
        codig.insert(0, valr[4])
        numCelula.insert(0, valr[5])
        precio_entry.insert(0, valr[6])
        cantida.insert(0, valr[7])   

    def seleccionado2():
        ElementoA2.delete(0, END)
        cantidad2.delete(0, END)
        codig2.delete(0, END)
        tip.delete(0, END)
        selected2=arbol2.focus() 
        valr2=arbol2.item(selected2, "values")
        ElementoA2.insert(0, valr2[0])
        cantidad2.insert(0, valr2[1])
        codig2.insert(0,valr2[2])
        tip.insert(0, valr2[3])
        
    def borrarregistro():
        remover=trev.selection()[0]
        trev.delete(remover)

    def eliminarcasillas(): 
        nombr.delete(0, END)
        apellid.delete(0, END)
        hor.delete(0, END)
        fech.delete(0, END)
        codig.delete(0, END)
        numCelula.delete(0, END)
        precio_entry.delete(0, END)
        cantida.delete(0, END)

    def enviardatos(): 
        nombredata=nombre.get()
        apellidodata=apellido.get() 
        horadata=hora.get()
        fechadata=fecha.get() 
        codigodata=codigo.get() 
        numCelulardata=numCelular.get()
        cursodata=curso.get()
        preciodata=precio_entry.get()
        cantidaddata=cantidad.get()
        print(nombredata, apellidodata, horadata, fechadata, codigodata, numCelulardata, cursodata,  cantidaddata)
        cadenaRegistro = nombredata + '|' + apellidodata + '|' + fechadata + '|' + str(codigodata) + '|' + str(numCelulardata) + '|' + cursodata + '|' + str(preciodata) + '|'  + str(cantidaddata) +'\n'
        validararchivo("ventas.txt")
        almacenaArchivo("ventas.txt", cadenaRegistro)
        trev.insert("", END,  text="Activo", values=(nombr.get(), apellid.get(), hor.get(), fech.get(), codig.get(), numCelula.get(), precio_entry.get(), cantida.get()))
    #-----------------------Cuerpo del programa-----------------------------------------------
    #---------Defino algunas variables que usare en diferentes funciones----------------------
    nombre=StringVar()
    apellido=StringVar() 
    hora=StringVar() 
    fecha=StringVar()
    codigo=IntVar() 
    numCelular=IntVar() 
    curso=StringVar()  
    prec=DoubleVar() 
    Elemento1=StringVar()
    codigo2=IntVar() 
    cantidad=IntVar() 
    tipo=StringVar()
    cantidad2A=IntVar()
    #---------------Panel de pestañas----------------------------------------------
    panel=ttk.Notebook(asados) 
    panel.pack(fill="both", expand="yes")   
    #Pestaña 1-------------------------------------------------------------------------------
    tab1=ttk.Frame(panel)
    panel.add(tab1, text="Ventas") 
    nombrA = Label(tab1, text="Nombres:").place(x=22, y=70)
    nombr = Entry(tab1, textvariable=nombre, width="40")
    nombr.place(x=22, y=100)
    apellidA=Label(tab1, text="Apellidos: ").place(x=22, y=130) 
    apellid=Entry(tab1, textvariable=apellido, width=40)
    apellid.place(x=22, y=160)
    horA=Label(tab1, text="Producto").place(x=22, y=190)
    hor=Entry(tab1, textvariable=hora, width="40")
    hor.place(x=22, y=220)
    fechA=Label(tab1, text="Fecha D/M/A: ").place(x=22, y=250) 
    fech=Entry(tab1, textvariable=fecha, width="40")
    fech.place(x=22, y=280)  
    codigA=Label(tab1, text="Código:").place(x=22, y=310)
    codig=Entry(tab1, textvariable=codigo, width="40")
    codig.place(x=22, y=340)
    numCelulaA=Label(tab1, text="Número celular: ").place(x=22, y=370)
    numCelula=Entry(tab1,textvariable=numCelular, width="40")
    numCelula.place(x=22, y=400)
    precio_label=Label(tab1, text="Precio: ").place(x=22, y=430)
    precio_entry=Entry(tab1, textvariable=prec, width="40")
    precio_entry.place(x=22, y=460)
    cantidaA=Label(tab1, text="Cantidad:").place(x=22, y=490)
    cantida=Entry(tab1, textvariable=cantidad, width="40")
    cantida.place(x=22, y=520)   
    #----------------Botones--------------------------------------------
    etiqueta=Label(tab1, text="Sección de registro de ventas").place(x=400, y=5)
    datost=Label(tab1, text="Para efectuar una venta y enviar los datos del cliente, clique el siguiente boton:").place(x=400, y=150)
    botonenviar=ttk.Button(tab1, text="Enviar datos de registro", command=enviardatos).place(x=400, y=100) 
    botonborrar=ttk.Button(tab1, text="Borrar un solo registro", command=borrarregistro).place(x=400, y=200)
    borrar1=Label(tab1, text="Para borrar un registro seleccione en la tabla inferior: La venta y presione el boton: Borrar un solo registro").place(x=400, y=250)
    editartext=Label(tab1,text="Para editar un registro seleccione: en la tabla inferior: La venta y presione el boton: Editar Registro, cuando halla cambiado los valores presione: Actualizar").place(x=400, y=300)
    acutalizar=ttk.Button(tab1, text="Actualizar edición", command=editarregistro ).place(x=400, y=350)
    borrarlabel=Label(tab1, text="Para limpiar los campos de entrada de texto pulse: Limpiar").place(x=400, y=400)
    botonlimpiar=ttk.Button(tab1, text="Limpiar", command=eliminarcasillas).place(x=400, y=450)
    labelusuario=Label(tab1, text="Tienda: " + usuario_entry.get(), font="Helvetica 20 bold", fg="red" ).place(x=700,  y=5)
    #Treeview--------------------
    trev=ttk.Treeview(tab1, columns=("col1", "col2", "col3", "col4", "col5", "col6", "col7", "col8"))
    trev.column("#0", width=150, anchor=CENTER)
    trev.heading("#0", text="Venta", anchor=CENTER)
    trev.column("col1", width=150, anchor=CENTER)
    trev.heading("col1", text="Nombre", anchor=CENTER)
    trev.column("col2", width=150, anchor=CENTER)
    trev.heading("col2", text="Apellido", anchor=CENTER)
    trev.column("col3", width=150, anchor=CENTER)
    trev.heading("col3", text="Producto", anchor=CENTER)
    trev.column("col4", width=150, anchor=CENTER)
    trev.heading("col4", text="Fecha", anchor=CENTER)
    trev.column("col5", width=150, anchor=CENTER)
    trev.heading("col5", text="Código", anchor=CENTER)
    trev.column("col6", width=150, anchor=CENTER)
    trev.heading("col6", text="Número Celular", anchor=CENTER)
    trev.column("col7", width=150, anchor=CENTER)
    trev.heading("col7", text="Precio", anchor=CENTER)
    trev.column("col8", width=150, anchor=CENTER)
    trev.heading("col8", text="Cantidad", anchor=CENTER)
    trev.place(y=700)

    #Pestaña 2 Inventario de recursos---------------------------------------------------------------------------------------------------------------------
    tab2=ttk.Frame(panel)
    ElementoA1 = Label(tab2, text="Nombre del elemento:").place(x=22, y=70)
    ElementoA2= Entry(tab2, textvariable=Elemento1, width="40")
    ElementoA2.place(x=22, y=100)
    cantidadA2=Label(tab2, text="Cantidad: ").place(x=22, y=130) 
    cantidad2=Entry(tab2, textvariable=cantidad2A, width=40)
    cantidad2.place(x=22, y=160) 
    codigA2=Label(tab2, text="Código/ID del elemento:").place(x=22, y=190)
    codig2=Entry(tab2, textvariable=codigo2, width="40")
    codig2.place(x=22, y=220)
    textotipo=Label(tab2, text="Precio").place(x=22, y=250)
    tip=Entry(tab2, textvariable=tipo, width="40")
    tip.place(x=22, y=280)
    botonenviar2=ttk.Button(tab2, text="Enviar Elementos", command=enviarelementos)
    botonenviar2.place(x=22, y=310)  
    botoneditar2=ttk.Button(tab2,text="Editar Registro", command=seleccionado2 ).place(x=22, y=340)
    editartext2=Label(tab2,text="Para editar unr egistre seleccione: en la tabla inferior: presione el boton: Editar Registro, cuando halla cambiado los valores presione: Actualizar").place(x=22, y=370)
    acutalizar2=ttk.Button(tab2, text="Actualizar edición", command=editregistroelemento)
    acutalizar2.place(x=22, y=400)
    #----------Botones-----------
    panel.add(tab2, text="Inventario de productos") 
    etiqueta2=Label(tab2, text="Sección para visualizar el inventario disponible: ").place(x=5, y=5) 
    #Treeview----------------------------------
    arbol2=ttk.Treeview(tab2, columns=("col1", "col2", "col3", "col4"))
    arbol2.column("#0", width=150, anchor=CENTER)
    arbol2.heading("#0", text="Listado Elementos", anchor=CENTER)
    arbol2.column("col1", width=150, anchor=CENTER)
    arbol2.heading("col1", text="Producto", anchor=CENTER)
    arbol2.column("col2", width=150, anchor=CENTER)
    arbol2.heading("col2", text="Cantidad", anchor=CENTER)
    arbol2.column("col3", width=150, anchor=CENTER)
    arbol2.heading("col3", text="Código:", anchor=CENTER)
    arbol2.column("col4", width=150, anchor=CENTER)
    arbol2.heading("col4", text="Precio", anchor=CENTER)
    arbol2.place(y=440) 
def empanadas(): 
    empanada=Toplevel()
    empanada.geometry("1400x1000")
    def almacenaArchivo(nombreFile, cadenaAlmacenar):
        print('Inicia Registro de Ventas')
        file=open(nombreFile,'a')
        file.write(cadenaAlmacenar)
        file.close()
        print('Finaliza Registro de venta')
        
    def validararchivo(nombreFile):
        if os.stat(nombreFile).st_size==0:
         cadenaEncabezado="NOMBRE | APELLIDO | FECHA | CODIGO | CELULAR | PRECIO | RECURSO | CANTIDAD \n"
         almacenaArchivo(nombreFile,cadenaEncabezado)

    def enviarelementos(): 
        arbol2.insert("", END, text="En Inventario", values=(ElementoA2.get(),cantidad2.get(), codig2.get(), tip.get()))
        ElementoA2.delete(0, END)
        cantidad2.delete(0, END)
        codig2.delete(0, END)
        tip.delete(0, END)

    def editarregistro():
        selected=trev.focus() 
        trev.item(selected, text="Vendido", values=(nombr.get(), apellid.get(), hor.get(), fech.get(), codig.get(), numCelula.get(), precio_entry.get(), cantida.get()))
        nombr.delete(0, END)
        apellid.delete(0, END)
        hor.delete(0, END)
        fech.delete(0, END)
        codig.delete(0, END)
        numCelula.delete(0, END)
        precio_entry.delete(0, END)
        cantida.delete(0, END)

    def editregistroelemento():
        selected2=arbol2.focus() 
        arbol2.item(selected2, text="En Inventario", values=(ElementoA2.get(), cantidad2.get(), codig2.get(), tip.get()))
        ElementoA2.delete(0, END)
        cantidad2.delete(0, END)
        codig2.delete(0, END)
        tip.delete(0, END)

    def seleccionado():
        nombr.delete(0, END)
        apellid.delete(0, END)
        hor.delete(0, END)
        fech.delete(0, END)
        codig.delete(0, END)
        numCelula.delete(0, END)
        precio_entry(0, END)
        cantida.delete(0, END)
        selected=trev.focus() 
        valr=trev.item(selected, "values")
        nombr.insert(0, valr[0])
        apellid.insert(0, valr[1])
        hor.insert(0, valr[2])
        fech.insert(0, valr[3])
        codig.insert(0, valr[4])
        numCelula.insert(0, valr[5])
        precio_entry.insert(0, valr[6])
        cantida.insert(0, valr[7])   

    def seleccionado2():
        ElementoA2.delete(0, END)
        cantidad2.delete(0, END)
        codig2.delete(0, END)
        tip.delete(0, END)
        selected2=arbol2.focus() 
        valr2=arbol2.item(selected2, "values")
        ElementoA2.insert(0, valr2[0])
        cantidad2.insert(0, valr2[1])
        codig2.insert(0,valr2[2])
        tip.insert(0, valr2[3])
        
    def borrarregistro():
        remover=trev.selection()[0]
        trev.delete(remover)

    def eliminarcasillas(): 
        nombr.delete(0, END)
        apellid.delete(0, END)
        hor.delete(0, END)
        fech.delete(0, END)
        codig.delete(0, END)
        numCelula.delete(0, END)
        precio_entry.delete(0, END)
        cantida.delete(0, END)

    def enviardatos(): 
        nombredata=nombre.get()
        apellidodata=apellido.get() 
        horadata=hora.get()
        fechadata=fecha.get() 
        codigodata=codigo.get() 
        numCelulardata=numCelular.get()
        cursodata=curso.get()
        preciodata=precio_entry.get()
        cantidaddata=cantidad.get()
        print(nombredata, apellidodata, horadata, fechadata, codigodata, numCelulardata, cursodata,  cantidaddata)
        cadenaRegistro = nombredata + '|' + apellidodata + '|' + fechadata + '|' + str(codigodata) + '|' + str(numCelulardata) + '|' + cursodata + '|' + str(preciodata) + '|'  + str(cantidaddata) +'\n'
        validararchivo("ventas.txt")
        almacenaArchivo("ventas.txt", cadenaRegistro)
        trev.insert("", END,  text="Activo", values=(nombr.get(), apellid.get(), hor.get(), fech.get(), codig.get(), numCelula.get(), precio_entry.get(), cantida.get()))
    #-----------------------Cuerpo del programa-----------------------------------------------
    #---------Defino algunas variables que usare en diferentes funciones----------------------
    nombre=StringVar()
    apellido=StringVar() 
    hora=StringVar() 
    fecha=StringVar()
    codigo=IntVar() 
    numCelular=IntVar() 
    curso=StringVar()  
    prec=DoubleVar() 
    Elemento1=StringVar()
    codigo2=IntVar() 
    cantidad=IntVar() 
    tipo=StringVar()
    cantidad2A=IntVar()
    #---------------Panel de pestañas----------------------------------------------
    panel=ttk.Notebook(empanada) 
    panel.pack(fill="both", expand="yes")   
    #Pestaña 1-------------------------------------------------------------------------------
    tab1=ttk.Frame(panel)
    panel.add(tab1, text="Ventas") 
    nombrA = Label(tab1, text="Nombres:").place(x=22, y=70)
    nombr = Entry(tab1, textvariable=nombre, width="40")
    nombr.place(x=22, y=100)
    apellidA=Label(tab1, text="Apellidos: ").place(x=22, y=130) 
    apellid=Entry(tab1, textvariable=apellido, width=40)
    apellid.place(x=22, y=160)
    horA=Label(tab1, text="Producto").place(x=22, y=190)
    hor=Entry(tab1, textvariable=hora, width="40")
    hor.place(x=22, y=220)
    fechA=Label(tab1, text="Fecha D/M/A: ").place(x=22, y=250) 
    fech=Entry(tab1, textvariable=fecha, width="40")
    fech.place(x=22, y=280)  
    codigA=Label(tab1, text="Código:").place(x=22, y=310)
    codig=Entry(tab1, textvariable=codigo, width="40")
    codig.place(x=22, y=340)
    numCelulaA=Label(tab1, text="Número celular: ").place(x=22, y=370)
    numCelula=Entry(tab1,textvariable=numCelular, width="40")
    numCelula.place(x=22, y=400)
    precio_label=Label(tab1, text="Precio: ").place(x=22, y=430)
    precio_entry=Entry(tab1, textvariable=prec, width="40")
    precio_entry.place(x=22, y=460)
    cantidaA=Label(tab1, text="Cantidad:").place(x=22, y=490)
    cantida=Entry(tab1, textvariable=cantidad, width="40")
    cantida.place(x=22, y=520)   
    #----------------Botones--------------------------------------------
    etiqueta=Label(tab1, text="Sección de registro de ventas").place(x=400, y=5)
    datost=Label(tab1, text="Para efectuar una venta y enviar los datos del cliente, clique el siguiente boton:").place(x=400, y=150)
    botonenviar=ttk.Button(tab1, text="Enviar datos de registro", command=enviardatos).place(x=400, y=100) 
    botonborrar=ttk.Button(tab1, text="Borrar un solo registro", command=borrarregistro).place(x=400, y=200)
    borrar1=Label(tab1, text="Para borrar un registro seleccione en la tabla inferior: La venta y presione el boton: Borrar un solo registro").place(x=400, y=250)
    editartext=Label(tab1,text="Para editar un registro seleccione: en la tabla inferior: La venta y presione el boton: Editar Registro, cuando halla cambiado los valores presione: Actualizar").place(x=400, y=300)
    acutalizar=ttk.Button(tab1, text="Actualizar edición", command=editarregistro ).place(x=400, y=350)
    borrarlabel=Label(tab1, text="Para limpiar los campos de entrada de texto pulse: Limpiar").place(x=400, y=400)
    botonlimpiar=ttk.Button(tab1, text="Limpiar", command=eliminarcasillas).place(x=400, y=450)
    labelusuario=Label(tab1, text="Tienda: " + usuario_entry.get(), font="Helvetica 20 bold", fg="red" ).place(x=700,  y=5)
    #Treeview--------------------
    trev=ttk.Treeview(tab1, columns=("col1", "col2", "col3", "col4", "col5", "col6", "col7", "col8"))
    trev.column("#0", width=150, anchor=CENTER)
    trev.heading("#0", text="Venta", anchor=CENTER)
    trev.column("col1", width=150, anchor=CENTER)
    trev.heading("col1", text="Nombre", anchor=CENTER)
    trev.column("col2", width=150, anchor=CENTER)
    trev.heading("col2", text="Apellido", anchor=CENTER)
    trev.column("col3", width=150, anchor=CENTER)
    trev.heading("col3", text="Producto", anchor=CENTER)
    trev.column("col4", width=150, anchor=CENTER)
    trev.heading("col4", text="Fecha", anchor=CENTER)
    trev.column("col5", width=150, anchor=CENTER)
    trev.heading("col5", text="Código", anchor=CENTER)
    trev.column("col6", width=150, anchor=CENTER)
    trev.heading("col6", text="Número Celular", anchor=CENTER)
    trev.column("col7", width=150, anchor=CENTER)
    trev.heading("col7", text="Precio", anchor=CENTER)
    trev.column("col8", width=150, anchor=CENTER)
    trev.heading("col8", text="Cantidad", anchor=CENTER)
    trev.place(y=700)

    #Pestaña 2 Inventario de recursos---------------------------------------------------------------------------------------------------------------------
    tab2=ttk.Frame(panel)
    ElementoA1 = Label(tab2, text="Nombre del elemento:").place(x=22, y=70)
    ElementoA2= Entry(tab2, textvariable=Elemento1, width="40")
    ElementoA2.place(x=22, y=100)
    cantidadA2=Label(tab2, text="Cantidad: ").place(x=22, y=130) 
    cantidad2=Entry(tab2, textvariable=cantidad2A, width=40)
    cantidad2.place(x=22, y=160) 
    codigA2=Label(tab2, text="Código/ID del elemento:").place(x=22, y=190)
    codig2=Entry(tab2, textvariable=codigo2, width="40")
    codig2.place(x=22, y=220)
    textotipo=Label(tab2, text="Precio").place(x=22, y=250)
    tip=Entry(tab2, textvariable=tipo, width="40")
    tip.place(x=22, y=280)
    botonenviar2=ttk.Button(tab2, text="Enviar Elementos", command=enviarelementos)
    botonenviar2.place(x=22, y=310)  
    botoneditar2=ttk.Button(tab2,text="Editar Registro", command=seleccionado2 ).place(x=22, y=340)
    editartext2=Label(tab2,text="Para editar unr egistre seleccione: en la tabla inferior: presione el boton: Editar Registro, cuando halla cambiado los valores presione: Actualizar").place(x=22, y=370)
    acutalizar2=ttk.Button(tab2, text="Actualizar edición", command=editregistroelemento)
    acutalizar2.place(x=22, y=400)
    #----------Botones-----------
    panel.add(tab2, text="Inventario de productos") 
    etiqueta2=Label(tab2, text="Sección para visualizar el inventario disponible: ").place(x=5, y=5) 
    #Treeview----------------------------------
    arbol2=ttk.Treeview(tab2, columns=("col1", "col2", "col3", "col4"))
    arbol2.column("#0", width=150, anchor=CENTER)
    arbol2.heading("#0", text="Listado Elementos", anchor=CENTER)
    arbol2.column("col1", width=150, anchor=CENTER)
    arbol2.heading("col1", text="Producto", anchor=CENTER)
    arbol2.column("col2", width=150, anchor=CENTER)
    arbol2.heading("col2", text="Cantidad", anchor=CENTER)
    arbol2.column("col3", width=150, anchor=CENTER)
    arbol2.heading("col3", text="Código:", anchor=CENTER)
    arbol2.column("col4", width=150, anchor=CENTER)
    arbol2.heading("col4", text="Precio", anchor=CENTER)
    arbol2.place(y=440) 
def samgung(): 
    sam=Toplevel()
    sam.geometry("1400x1000")
    def almacenaArchivo(nombreFile, cadenaAlmacenar):
        print('Inicia Registro de Ventas')
        file=open(nombreFile,'a')
        file.write(cadenaAlmacenar)
        file.close()
        print('Finaliza Registro de venta')
        
    def validararchivo(nombreFile):
        if os.stat(nombreFile).st_size==0:
         cadenaEncabezado="NOMBRE | APELLIDO | FECHA | CODIGO | CELULAR | PRECIO | RECURSO | CANTIDAD \n"
         almacenaArchivo(nombreFile,cadenaEncabezado)

    def enviarelementos(): 
        arbol2.insert("", END, text="En Inventario", values=(ElementoA2.get(),cantidad2.get(), codig2.get(), tip.get()))
        ElementoA2.delete(0, END)
        cantidad2.delete(0, END)
        codig2.delete(0, END)
        tip.delete(0, END)

    def editarregistro():
        selected=trev.focus() 
        trev.item(selected, text="Vendido", values=(nombr.get(), apellid.get(), hor.get(), fech.get(), codig.get(), numCelula.get(), precio_entry.get(), cantida.get()))
        nombr.delete(0, END)
        apellid.delete(0, END)
        hor.delete(0, END)
        fech.delete(0, END)
        codig.delete(0, END)
        numCelula.delete(0, END)
        precio_entry.delete(0, END)
        cantida.delete(0, END)

    def editregistroelemento():
        selected2=arbol2.focus() 
        arbol2.item(selected2, text="En Inventario", values=(ElementoA2.get(), cantidad2.get(), codig2.get(), tip.get()))
        ElementoA2.delete(0, END)
        cantidad2.delete(0, END)
        codig2.delete(0, END)
        tip.delete(0, END)

    def seleccionado():
        nombr.delete(0, END)
        apellid.delete(0, END)
        hor.delete(0, END)
        fech.delete(0, END)
        codig.delete(0, END)
        numCelula.delete(0, END)
        precio_entry(0, END)
        cantida.delete(0, END)
        selected=trev.focus() 
        valr=trev.item(selected, "values")
        nombr.insert(0, valr[0])
        apellid.insert(0, valr[1])
        hor.insert(0, valr[2])
        fech.insert(0, valr[3])
        codig.insert(0, valr[4])
        numCelula.insert(0, valr[5])
        precio_entry.insert(0, valr[6])
        cantida.insert(0, valr[7])   

    def seleccionado2():
        ElementoA2.delete(0, END)
        cantidad2.delete(0, END)
        codig2.delete(0, END)
        tip.delete(0, END)
        selected2=arbol2.focus() 
        valr2=arbol2.item(selected2, "values")
        ElementoA2.insert(0, valr2[0])
        cantidad2.insert(0, valr2[1])
        codig2.insert(0,valr2[2])
        tip.insert(0, valr2[3])
        
    def borrarregistro():
        remover=trev.selection()[0]
        trev.delete(remover)

    def eliminarcasillas(): 
        nombr.delete(0, END)
        apellid.delete(0, END)
        hor.delete(0, END)
        fech.delete(0, END)
        codig.delete(0, END)
        numCelula.delete(0, END)
        precio_entry.delete(0, END)
        cantida.delete(0, END)

    def enviardatos(): 
        nombredata=nombre.get()
        apellidodata=apellido.get() 
        horadata=hora.get()
        fechadata=fecha.get() 
        codigodata=codigo.get() 
        numCelulardata=numCelular.get()
        cursodata=curso.get()
        preciodata=precio_entry.get()
        cantidaddata=cantidad.get()
        print(nombredata, apellidodata, horadata, fechadata, codigodata, numCelulardata, cursodata,  cantidaddata)
        cadenaRegistro = nombredata + '|' + apellidodata + '|' + fechadata + '|' + str(codigodata) + '|' + str(numCelulardata) + '|' + cursodata + '|' + str(preciodata) + '|'  + str(cantidaddata) +'\n'
        validararchivo("ventas.txt")
        almacenaArchivo("ventas.txt", cadenaRegistro)
        trev.insert("", END,  text="Activo", values=(nombr.get(), apellid.get(), hor.get(), fech.get(), codig.get(), numCelula.get(), precio_entry.get(), cantida.get()))
    #-----------------------Cuerpo del programa-----------------------------------------------
    #---------Defino algunas variables que usare en diferentes funciones----------------------
    nombre=StringVar()
    apellido=StringVar() 
    hora=StringVar() 
    fecha=StringVar()
    codigo=IntVar() 
    numCelular=IntVar() 
    curso=StringVar()  
    prec=DoubleVar() 
    Elemento1=StringVar()
    codigo2=IntVar() 
    cantidad=IntVar() 
    tipo=StringVar()
    cantidad2A=IntVar()
    #---------------Panel de pestañas----------------------------------------------
    panel=ttk.Notebook(sam) 
    panel.pack(fill="both", expand="yes")   
    #Pestaña 1-------------------------------------------------------------------------------
    tab1=ttk.Frame(panel)
    panel.add(tab1, text="Ventas") 
    nombrA = Label(tab1, text="Nombres:").place(x=22, y=70)
    nombr = Entry(tab1, textvariable=nombre, width="40")
    nombr.place(x=22, y=100)
    apellidA=Label(tab1, text="Apellidos: ").place(x=22, y=130) 
    apellid=Entry(tab1, textvariable=apellido, width=40)
    apellid.place(x=22, y=160)
    horA=Label(tab1, text="Producto").place(x=22, y=190)
    hor=Entry(tab1, textvariable=hora, width="40")
    hor.place(x=22, y=220)
    fechA=Label(tab1, text="Fecha D/M/A: ").place(x=22, y=250) 
    fech=Entry(tab1, textvariable=fecha, width="40")
    fech.place(x=22, y=280)  
    codigA=Label(tab1, text="Código:").place(x=22, y=310)
    codig=Entry(tab1, textvariable=codigo, width="40")
    codig.place(x=22, y=340)
    numCelulaA=Label(tab1, text="Número celular: ").place(x=22, y=370)
    numCelula=Entry(tab1,textvariable=numCelular, width="40")
    numCelula.place(x=22, y=400)
    precio_label=Label(tab1, text="Precio: ").place(x=22, y=430)
    precio_entry=Entry(tab1, textvariable=prec, width="40")
    precio_entry.place(x=22, y=460)
    cantidaA=Label(tab1, text="Cantidad:").place(x=22, y=490)
    cantida=Entry(tab1, textvariable=cantidad, width="40")
    cantida.place(x=22, y=520)   
    #----------------Botones--------------------------------------------
    etiqueta=Label(tab1, text="Sección de registro de ventas").place(x=400, y=5)
    datost=Label(tab1, text="Para efectuar una venta y enviar los datos del cliente, clique el siguiente boton:").place(x=400, y=150)
    botonenviar=ttk.Button(tab1, text="Enviar datos de registro", command=enviardatos).place(x=400, y=100) 
    botonborrar=ttk.Button(tab1, text="Borrar un solo registro", command=borrarregistro).place(x=400, y=200)
    borrar1=Label(tab1, text="Para borrar un registro seleccione en la tabla inferior: La venta y presione el boton: Borrar un solo registro").place(x=400, y=250)
    editartext=Label(tab1,text="Para editar un registro seleccione: en la tabla inferior: La venta y presione el boton: Editar Registro, cuando halla cambiado los valores presione: Actualizar").place(x=400, y=300)
    acutalizar=ttk.Button(tab1, text="Actualizar edición", command=editarregistro ).place(x=400, y=350)
    borrarlabel=Label(tab1, text="Para limpiar los campos de entrada de texto pulse: Limpiar").place(x=400, y=400)
    botonlimpiar=ttk.Button(tab1, text="Limpiar", command=eliminarcasillas).place(x=400, y=450)
    labelusuario=Label(tab1, text="Tienda: " + usuario_entry.get(), font="Helvetica 20 bold", fg="red" ).place(x=700,  y=5)
    #Treeview--------------------
    trev=ttk.Treeview(tab1, columns=("col1", "col2", "col3", "col4", "col5", "col6", "col7", "col8"))
    trev.column("#0", width=150, anchor=CENTER)
    trev.heading("#0", text="Venta", anchor=CENTER)
    trev.column("col1", width=150, anchor=CENTER)
    trev.heading("col1", text="Nombre", anchor=CENTER)
    trev.column("col2", width=150, anchor=CENTER)
    trev.heading("col2", text="Apellido", anchor=CENTER)
    trev.column("col3", width=150, anchor=CENTER)
    trev.heading("col3", text="Producto", anchor=CENTER)
    trev.column("col4", width=150, anchor=CENTER)
    trev.heading("col4", text="Fecha", anchor=CENTER)
    trev.column("col5", width=150, anchor=CENTER)
    trev.heading("col5", text="Código", anchor=CENTER)
    trev.column("col6", width=150, anchor=CENTER)
    trev.heading("col6", text="Número Celular", anchor=CENTER)
    trev.column("col7", width=150, anchor=CENTER)
    trev.heading("col7", text="Precio", anchor=CENTER)
    trev.column("col8", width=150, anchor=CENTER)
    trev.heading("col8", text="Cantidad", anchor=CENTER)
    trev.place(y=700)

    #Pestaña 2 Inventario de recursos---------------------------------------------------------------------------------------------------------------------
    tab2=ttk.Frame(panel)
    ElementoA1 = Label(tab2, text="Nombre del elemento:").place(x=22, y=70)
    ElementoA2= Entry(tab2, textvariable=Elemento1, width="40")
    ElementoA2.place(x=22, y=100)
    cantidadA2=Label(tab2, text="Cantidad: ").place(x=22, y=130) 
    cantidad2=Entry(tab2, textvariable=cantidad2A, width=40)
    cantidad2.place(x=22, y=160) 
    codigA2=Label(tab2, text="Código/ID del elemento:").place(x=22, y=190)
    codig2=Entry(tab2, textvariable=codigo2, width="40")
    codig2.place(x=22, y=220)
    textotipo=Label(tab2, text="Precio").place(x=22, y=250)
    tip=Entry(tab2, textvariable=tipo, width="40")
    tip.place(x=22, y=280)
    botonenviar2=ttk.Button(tab2, text="Enviar Elementos", command=enviarelementos)
    botonenviar2.place(x=22, y=310)  
    botoneditar2=ttk.Button(tab2,text="Editar Registro", command=seleccionado2 ).place(x=22, y=340)
    editartext2=Label(tab2,text="Para editar unr egistre seleccione: en la tabla inferior: presione el boton: Editar Registro, cuando halla cambiado los valores presione: Actualizar").place(x=22, y=370)
    acutalizar2=ttk.Button(tab2, text="Actualizar edición", command=editregistroelemento)
    acutalizar2.place(x=22, y=400)
    #----------Botones-----------
    panel.add(tab2, text="Inventario de productos") 
    etiqueta2=Label(tab2, text="Sección para visualizar el inventario disponible: ").place(x=5, y=5) 
    #Treeview----------------------------------
    arbol2=ttk.Treeview(tab2, columns=("col1", "col2", "col3", "col4"))
    arbol2.column("#0", width=150, anchor=CENTER)
    arbol2.heading("#0", text="Listado Elementos", anchor=CENTER)
    arbol2.column("col1", width=150, anchor=CENTER)
    arbol2.heading("col1", text="Producto", anchor=CENTER)
    arbol2.column("col2", width=150, anchor=CENTER)
    arbol2.heading("col2", text="Cantidad", anchor=CENTER)
    arbol2.column("col3", width=150, anchor=CENTER)
    arbol2.heading("col3", text="Código:", anchor=CENTER)
    arbol2.column("col4", width=150, anchor=CENTER)
    arbol2.heading("col4", text="Precio", anchor=CENTER)
    arbol2.place(y=440) 
def applepera(): 
    app=Toplevel()
    app.geometry("1400x1000")
    def almacenaArchivo(nombreFile, cadenaAlmacenar):
        print('Inicia Registro de Ventas')
        file=open(nombreFile,'a')
        file.write(cadenaAlmacenar)
        file.close()
        print('Finaliza Registro de venta')
        
    def validararchivo(nombreFile):
        if os.stat(nombreFile).st_size==0:
         cadenaEncabezado="NOMBRE | APELLIDO | FECHA | CODIGO | CELULAR | PRECIO | RECURSO | CANTIDAD \n"
         almacenaArchivo(nombreFile,cadenaEncabezado)

    def enviarelementos(): 
        arbol2.insert("", END, text="En Inventario", values=(ElementoA2.get(),cantidad2.get(), codig2.get(), tip.get()))
        ElementoA2.delete(0, END)
        cantidad2.delete(0, END)
        codig2.delete(0, END)
        tip.delete(0, END)

    def editarregistro():
        selected=trev.focus() 
        trev.item(selected, text="Vendido", values=(nombr.get(), apellid.get(), hor.get(), fech.get(), codig.get(), numCelula.get(), precio_entry.get(), cantida.get()))
        nombr.delete(0, END)
        apellid.delete(0, END)
        hor.delete(0, END)
        fech.delete(0, END)
        codig.delete(0, END)
        numCelula.delete(0, END)
        precio_entry.delete(0, END)
        cantida.delete(0, END)

    def editregistroelemento():
        selected2=arbol2.focus() 
        arbol2.item(selected2, text="En Inventario", values=(ElementoA2.get(), cantidad2.get(), codig2.get(), tip.get()))
        ElementoA2.delete(0, END)
        cantidad2.delete(0, END)
        codig2.delete(0, END)
        tip.delete(0, END)

    def seleccionado():
        nombr.delete(0, END)
        apellid.delete(0, END)
        hor.delete(0, END)
        fech.delete(0, END)
        codig.delete(0, END)
        numCelula.delete(0, END)
        precio_entry(0, END)
        cantida.delete(0, END)
        selected=trev.focus() 
        valr=trev.item(selected, "values")
        nombr.insert(0, valr[0])
        apellid.insert(0, valr[1])
        hor.insert(0, valr[2])
        fech.insert(0, valr[3])
        codig.insert(0, valr[4])
        numCelula.insert(0, valr[5])
        precio_entry.insert(0, valr[6])
        cantida.insert(0, valr[7])   

    def seleccionado2():
        ElementoA2.delete(0, END)
        cantidad2.delete(0, END)
        codig2.delete(0, END)
        tip.delete(0, END)
        selected2=arbol2.focus() 
        valr2=arbol2.item(selected2, "values")
        ElementoA2.insert(0, valr2[0])
        cantidad2.insert(0, valr2[1])
        codig2.insert(0,valr2[2])
        tip.insert(0, valr2[3])
        
    def borrarregistro():
        remover=trev.selection()[0]
        trev.delete(remover)

    def eliminarcasillas(): 
        nombr.delete(0, END)
        apellid.delete(0, END)
        hor.delete(0, END)
        fech.delete(0, END)
        codig.delete(0, END)
        numCelula.delete(0, END)
        precio_entry.delete(0, END)
        cantida.delete(0, END)

    def enviardatos(): 
        nombredata=nombre.get()
        apellidodata=apellido.get() 
        horadata=hora.get()
        fechadata=fecha.get() 
        codigodata=codigo.get() 
        numCelulardata=numCelular.get()
        cursodata=curso.get()
        preciodata=precio_entry.get()
        cantidaddata=cantidad.get()
        print(nombredata, apellidodata, horadata, fechadata, codigodata, numCelulardata, cursodata,  cantidaddata)
        cadenaRegistro = nombredata + '|' + apellidodata + '|' + fechadata + '|' + str(codigodata) + '|' + str(numCelulardata) + '|' + cursodata + '|' + str(preciodata) + '|'  + str(cantidaddata) +'\n'
        validararchivo("ventas.txt")
        almacenaArchivo("ventas.txt", cadenaRegistro)
        trev.insert("", END,  text="Activo", values=(nombr.get(), apellid.get(), hor.get(), fech.get(), codig.get(), numCelula.get(), precio_entry.get(), cantida.get()))
    #-----------------------Cuerpo del programa-----------------------------------------------
    #---------Defino algunas variables que usare en diferentes funciones----------------------
    nombre=StringVar()
    apellido=StringVar() 
    hora=StringVar() 
    fecha=StringVar()
    codigo=IntVar() 
    numCelular=IntVar() 
    curso=StringVar()  
    prec=DoubleVar() 
    Elemento1=StringVar()
    codigo2=IntVar() 
    cantidad=IntVar() 
    tipo=StringVar()
    cantidad2A=IntVar()
    #---------------Panel de pestañas----------------------------------------------
    panel=ttk.Notebook(app) 
    panel.pack(fill="both", expand="yes")   
    #Pestaña 1-------------------------------------------------------------------------------
    tab1=ttk.Frame(panel)
    panel.add(tab1, text="Ventas") 
    nombrA = Label(tab1, text="Nombres:").place(x=22, y=70)
    nombr = Entry(tab1, textvariable=nombre, width="40")
    nombr.place(x=22, y=100)
    apellidA=Label(tab1, text="Apellidos: ").place(x=22, y=130) 
    apellid=Entry(tab1, textvariable=apellido, width=40)
    apellid.place(x=22, y=160)
    horA=Label(tab1, text="Producto").place(x=22, y=190)
    hor=Entry(tab1, textvariable=hora, width="40")
    hor.place(x=22, y=220)
    fechA=Label(tab1, text="Fecha D/M/A: ").place(x=22, y=250) 
    fech=Entry(tab1, textvariable=fecha, width="40")
    fech.place(x=22, y=280)  
    codigA=Label(tab1, text="Código:").place(x=22, y=310)
    codig=Entry(tab1, textvariable=codigo, width="40")
    codig.place(x=22, y=340)
    numCelulaA=Label(tab1, text="Número celular: ").place(x=22, y=370)
    numCelula=Entry(tab1,textvariable=numCelular, width="40")
    numCelula.place(x=22, y=400)
    precio_label=Label(tab1, text="Precio: ").place(x=22, y=430)
    precio_entry=Entry(tab1, textvariable=prec, width="40")
    precio_entry.place(x=22, y=460)
    cantidaA=Label(tab1, text="Cantidad:").place(x=22, y=490)
    cantida=Entry(tab1, textvariable=cantidad, width="40")
    cantida.place(x=22, y=520)   
    #----------------Botones--------------------------------------------
    etiqueta=Label(tab1, text="Sección de registro de ventas").place(x=400, y=5)
    datost=Label(tab1, text="Para efectuar una venta y enviar los datos del cliente, clique el siguiente boton:").place(x=400, y=150)
    botonenviar=ttk.Button(tab1, text="Enviar datos de registro", command=enviardatos).place(x=400, y=100) 
    botonborrar=ttk.Button(tab1, text="Borrar un solo registro", command=borrarregistro).place(x=400, y=200)
    borrar1=Label(tab1, text="Para borrar un registro seleccione en la tabla inferior: La venta y presione el boton: Borrar un solo registro").place(x=400, y=250)
    editartext=Label(tab1,text="Para editar un registro seleccione: en la tabla inferior: La venta y presione el boton: Editar Registro, cuando halla cambiado los valores presione: Actualizar").place(x=400, y=300)
    acutalizar=ttk.Button(tab1, text="Actualizar edición", command=editarregistro ).place(x=400, y=350)
    borrarlabel=Label(tab1, text="Para limpiar los campos de entrada de texto pulse: Limpiar").place(x=400, y=400)
    botonlimpiar=ttk.Button(tab1, text="Limpiar", command=eliminarcasillas).place(x=400, y=450)
    labelusuario=Label(tab1, text="Tienda: " + usuario_entry.get(), font="Helvetica 20 bold", fg="red" ).place(x=700,  y=5)
    #Treeview--------------------
    trev=ttk.Treeview(tab1, columns=("col1", "col2", "col3", "col4", "col5", "col6", "col7", "col8"))
    trev.column("#0", width=150, anchor=CENTER)
    trev.heading("#0", text="Venta", anchor=CENTER)
    trev.column("col1", width=150, anchor=CENTER)
    trev.heading("col1", text="Nombre", anchor=CENTER)
    trev.column("col2", width=150, anchor=CENTER)
    trev.heading("col2", text="Apellido", anchor=CENTER)
    trev.column("col3", width=150, anchor=CENTER)
    trev.heading("col3", text="Producto", anchor=CENTER)
    trev.column("col4", width=150, anchor=CENTER)
    trev.heading("col4", text="Fecha", anchor=CENTER)
    trev.column("col5", width=150, anchor=CENTER)
    trev.heading("col5", text="Código", anchor=CENTER)
    trev.column("col6", width=150, anchor=CENTER)
    trev.heading("col6", text="Número Celular", anchor=CENTER)
    trev.column("col7", width=150, anchor=CENTER)
    trev.heading("col7", text="Precio", anchor=CENTER)
    trev.column("col8", width=150, anchor=CENTER)
    trev.heading("col8", text="Cantidad", anchor=CENTER)
    trev.place(y=700)

    #Pestaña 2 Inventario de recursos---------------------------------------------------------------------------------------------------------------------
    tab2=ttk.Frame(panel)
    ElementoA1 = Label(tab2, text="Nombre del elemento:").place(x=22, y=70)
    ElementoA2= Entry(tab2, textvariable=Elemento1, width="40")
    ElementoA2.place(x=22, y=100)
    cantidadA2=Label(tab2, text="Cantidad: ").place(x=22, y=130) 
    cantidad2=Entry(tab2, textvariable=cantidad2A, width=40)
    cantidad2.place(x=22, y=160) 
    codigA2=Label(tab2, text="Código/ID del elemento:").place(x=22, y=190)
    codig2=Entry(tab2, textvariable=codigo2, width="40")
    codig2.place(x=22, y=220)
    textotipo=Label(tab2, text="Precio").place(x=22, y=250)
    tip=Entry(tab2, textvariable=tipo, width="40")
    tip.place(x=22, y=280)
    botonenviar2=ttk.Button(tab2, text="Enviar Elementos", command=enviarelementos)
    botonenviar2.place(x=22, y=310)  
    botoneditar2=ttk.Button(tab2,text="Editar Registro", command=seleccionado2 ).place(x=22, y=340)
    editartext2=Label(tab2,text="Para editar unr egistre seleccione: en la tabla inferior: presione el boton: Editar Registro, cuando halla cambiado los valores presione: Actualizar").place(x=22, y=370)
    acutalizar2=ttk.Button(tab2, text="Actualizar edición", command=editregistroelemento)
    acutalizar2.place(x=22, y=400)
    #----------Botones-----------
    panel.add(tab2, text="Inventario de productos") 
    etiqueta2=Label(tab2, text="Sección para visualizar el inventario disponible: ").place(x=5, y=5) 
    #Treeview----------------------------------
    arbol2=ttk.Treeview(tab2, columns=("col1", "col2", "col3", "col4"))
    arbol2.column("#0", width=150, anchor=CENTER)
    arbol2.heading("#0", text="Listado Elementos", anchor=CENTER)
    arbol2.column("col1", width=150, anchor=CENTER)
    arbol2.heading("col1", text="Producto", anchor=CENTER)
    arbol2.column("col2", width=150, anchor=CENTER)
    arbol2.heading("col2", text="Cantidad", anchor=CENTER)
    arbol2.column("col3", width=150, anchor=CENTER)
    arbol2.heading("col3", text="Código:", anchor=CENTER)
    arbol2.column("col4", width=150, anchor=CENTER)
    arbol2.heading("col4", text="Precio", anchor=CENTER)
    arbol2.place(y=440) 
def tecnicos(): 
    tec=Toplevel()
    tec.geometry("1400x1000")
    def almacenaArchivo(nombreFile, cadenaAlmacenar):
        print('Inicia Registro de Ventas')
        file=open(nombreFile,'a')
        file.write(cadenaAlmacenar)
        file.close()
        print('Finaliza Registro de venta')
        
    def validararchivo(nombreFile):
        if os.stat(nombreFile).st_size==0:
         cadenaEncabezado="NOMBRE | APELLIDO | FECHA | CODIGO | CELULAR | PRECIO | RECURSO | CANTIDAD \n"
         almacenaArchivo(nombreFile,cadenaEncabezado)

    def enviarelementos(): 
        arbol2.insert("", END, text="En Inventario", values=(ElementoA2.get(),cantidad2.get(), codig2.get(), tip.get()))
        ElementoA2.delete(0, END)
        cantidad2.delete(0, END)
        codig2.delete(0, END)
        tip.delete(0, END)

    def editarregistro():
        selected=trev.focus() 
        trev.item(selected, text="Vendido", values=(nombr.get(), apellid.get(), hor.get(), fech.get(), codig.get(), numCelula.get(), precio_entry.get(), cantida.get()))
        nombr.delete(0, END)
        apellid.delete(0, END)
        hor.delete(0, END)
        fech.delete(0, END)
        codig.delete(0, END)
        numCelula.delete(0, END)
        precio_entry.delete(0, END)
        cantida.delete(0, END)

    def editregistroelemento():
        selected2=arbol2.focus() 
        arbol2.item(selected2, text="En Inventario", values=(ElementoA2.get(), cantidad2.get(), codig2.get(), tip.get()))
        ElementoA2.delete(0, END)
        cantidad2.delete(0, END)
        codig2.delete(0, END)
        tip.delete(0, END)

    def seleccionado():
        nombr.delete(0, END)
        apellid.delete(0, END)
        hor.delete(0, END)
        fech.delete(0, END)
        codig.delete(0, END)
        numCelula.delete(0, END)
        precio_entry(0, END)
        cantida.delete(0, END)
        selected=trev.focus() 
        valr=trev.item(selected, "values")
        nombr.insert(0, valr[0])
        apellid.insert(0, valr[1])
        hor.insert(0, valr[2])
        fech.insert(0, valr[3])
        codig.insert(0, valr[4])
        numCelula.insert(0, valr[5])
        precio_entry.insert(0, valr[6])
        cantida.insert(0, valr[7])   

    def seleccionado2():
        ElementoA2.delete(0, END)
        cantidad2.delete(0, END)
        codig2.delete(0, END)
        tip.delete(0, END)
        selected2=arbol2.focus() 
        valr2=arbol2.item(selected2, "values")
        ElementoA2.insert(0, valr2[0])
        cantidad2.insert(0, valr2[1])
        codig2.insert(0,valr2[2])
        tip.insert(0, valr2[3])
        
    def borrarregistro():
        remover=trev.selection()[0]
        trev.delete(remover)

    def eliminarcasillas(): 
        nombr.delete(0, END)
        apellid.delete(0, END)
        hor.delete(0, END)
        fech.delete(0, END)
        codig.delete(0, END)
        numCelula.delete(0, END)
        precio_entry.delete(0, END)
        cantida.delete(0, END)

    def enviardatos(): 
        nombredata=nombre.get()
        apellidodata=apellido.get() 
        horadata=hora.get()
        fechadata=fecha.get() 
        codigodata=codigo.get() 
        numCelulardata=numCelular.get()
        cursodata=curso.get()
        preciodata=precio_entry.get()
        cantidaddata=cantidad.get()
        print(nombredata, apellidodata, horadata, fechadata, codigodata, numCelulardata, cursodata,  cantidaddata)
        cadenaRegistro = nombredata + '|' + apellidodata + '|' + fechadata + '|' + str(codigodata) + '|' + str(numCelulardata) + '|' + cursodata + '|' + str(preciodata) + '|'  + str(cantidaddata) +'\n'
        validararchivo("ventas.txt")
        almacenaArchivo("ventas.txt", cadenaRegistro)
        trev.insert("", END,  text="Activo", values=(nombr.get(), apellid.get(), hor.get(), fech.get(), codig.get(), numCelula.get(), precio_entry.get(), cantida.get()))
    #-----------------------Cuerpo del programa-----------------------------------------------
    #---------Defino algunas variables que usare en diferentes funciones----------------------
    nombre=StringVar()
    apellido=StringVar() 
    hora=StringVar() 
    fecha=StringVar()
    codigo=IntVar() 
    numCelular=IntVar() 
    curso=StringVar()  
    prec=DoubleVar() 
    Elemento1=StringVar()
    codigo2=IntVar() 
    cantidad=IntVar() 
    tipo=StringVar()
    cantidad2A=IntVar()
    #---------------Panel de pestañas----------------------------------------------
    panel=ttk.Notebook(tec) 
    panel.pack(fill="both", expand="yes")   
    #Pestaña 1-------------------------------------------------------------------------------
    tab1=ttk.Frame(panel)
    panel.add(tab1, text="Ventas") 
    nombrA = Label(tab1, text="Nombres:").place(x=22, y=70)
    nombr = Entry(tab1, textvariable=nombre, width="40")
    nombr.place(x=22, y=100)
    apellidA=Label(tab1, text="Apellidos: ").place(x=22, y=130) 
    apellid=Entry(tab1, textvariable=apellido, width=40)
    apellid.place(x=22, y=160)
    horA=Label(tab1, text="Producto").place(x=22, y=190)
    hor=Entry(tab1, textvariable=hora, width="40")
    hor.place(x=22, y=220)
    fechA=Label(tab1, text="Fecha D/M/A: ").place(x=22, y=250) 
    fech=Entry(tab1, textvariable=fecha, width="40")
    fech.place(x=22, y=280)  
    codigA=Label(tab1, text="Código:").place(x=22, y=310)
    codig=Entry(tab1, textvariable=codigo, width="40")
    codig.place(x=22, y=340)
    numCelulaA=Label(tab1, text="Número celular: ").place(x=22, y=370)
    numCelula=Entry(tab1,textvariable=numCelular, width="40")
    numCelula.place(x=22, y=400)
    precio_label=Label(tab1, text="Precio: ").place(x=22, y=430)
    precio_entry=Entry(tab1, textvariable=prec, width="40")
    precio_entry.place(x=22, y=460)
    cantidaA=Label(tab1, text="Cantidad:").place(x=22, y=490)
    cantida=Entry(tab1, textvariable=cantidad, width="40")
    cantida.place(x=22, y=520)   
    #----------------Botones--------------------------------------------
    etiqueta=Label(tab1, text="Sección de registro de ventas").place(x=400, y=5)
    datost=Label(tab1, text="Para efectuar una venta y enviar los datos del cliente, clique el siguiente boton:").place(x=400, y=150)
    botonenviar=ttk.Button(tab1, text="Enviar datos de registro", command=enviardatos).place(x=400, y=100) 
    botonborrar=ttk.Button(tab1, text="Borrar un solo registro", command=borrarregistro).place(x=400, y=200)
    borrar1=Label(tab1, text="Para borrar un registro seleccione en la tabla inferior: La venta y presione el boton: Borrar un solo registro").place(x=400, y=250)
    editartext=Label(tab1,text="Para editar un registro seleccione: en la tabla inferior: La venta y presione el boton: Editar Registro, cuando halla cambiado los valores presione: Actualizar").place(x=400, y=300)
    acutalizar=ttk.Button(tab1, text="Actualizar edición", command=editarregistro ).place(x=400, y=350)
    borrarlabel=Label(tab1, text="Para limpiar los campos de entrada de texto pulse: Limpiar").place(x=400, y=400)
    botonlimpiar=ttk.Button(tab1, text="Limpiar", command=eliminarcasillas).place(x=400, y=450)
    labelusuario=Label(tab1, text="Tienda: " + usuario_entry.get(), font="Helvetica 20 bold", fg="red" ).place(x=700,  y=5)
    #Treeview--------------------
    trev=ttk.Treeview(tab1, columns=("col1", "col2", "col3", "col4", "col5", "col6", "col7", "col8"))
    trev.column("#0", width=150, anchor=CENTER)
    trev.heading("#0", text="Venta", anchor=CENTER)
    trev.column("col1", width=150, anchor=CENTER)
    trev.heading("col1", text="Nombre", anchor=CENTER)
    trev.column("col2", width=150, anchor=CENTER)
    trev.heading("col2", text="Apellido", anchor=CENTER)
    trev.column("col3", width=150, anchor=CENTER)
    trev.heading("col3", text="Producto", anchor=CENTER)
    trev.column("col4", width=150, anchor=CENTER)
    trev.heading("col4", text="Fecha", anchor=CENTER)
    trev.column("col5", width=150, anchor=CENTER)
    trev.heading("col5", text="Código", anchor=CENTER)
    trev.column("col6", width=150, anchor=CENTER)
    trev.heading("col6", text="Número Celular", anchor=CENTER)
    trev.column("col7", width=150, anchor=CENTER)
    trev.heading("col7", text="Precio", anchor=CENTER)
    trev.column("col8", width=150, anchor=CENTER)
    trev.heading("col8", text="Cantidad", anchor=CENTER)
    trev.place(y=700)

    #Pestaña 2 Inventario de recursos---------------------------------------------------------------------------------------------------------------------
    tab2=ttk.Frame(panel)
    ElementoA1 = Label(tab2, text="Nombre del elemento:").place(x=22, y=70)
    ElementoA2= Entry(tab2, textvariable=Elemento1, width="40")
    ElementoA2.place(x=22, y=100)
    cantidadA2=Label(tab2, text="Cantidad: ").place(x=22, y=130) 
    cantidad2=Entry(tab2, textvariable=cantidad2A, width=40)
    cantidad2.place(x=22, y=160) 
    codigA2=Label(tab2, text="Código/ID del elemento:").place(x=22, y=190)
    codig2=Entry(tab2, textvariable=codigo2, width="40")
    codig2.place(x=22, y=220)
    textotipo=Label(tab2, text="Precio").place(x=22, y=250)
    tip=Entry(tab2, textvariable=tipo, width="40")
    tip.place(x=22, y=280)
    botonenviar2=ttk.Button(tab2, text="Enviar Elementos", command=enviarelementos)
    botonenviar2.place(x=22, y=310)  
    botoneditar2=ttk.Button(tab2,text="Editar Registro", command=seleccionado2 ).place(x=22, y=340)
    editartext2=Label(tab2,text="Para editar unr egistre seleccione: en la tabla inferior: presione el boton: Editar Registro, cuando halla cambiado los valores presione: Actualizar").place(x=22, y=370)
    acutalizar2=ttk.Button(tab2, text="Actualizar edición", command=editregistroelemento)
    acutalizar2.place(x=22, y=400)
    #----------Botones-----------
    panel.add(tab2, text="Inventario de productos") 
    etiqueta2=Label(tab2, text="Sección para visualizar el inventario disponible: ").place(x=5, y=5) 
    #Treeview----------------------------------
    arbol2=ttk.Treeview(tab2, columns=("col1", "col2", "col3", "col4"))
    arbol2.column("#0", width=150, anchor=CENTER)
    arbol2.heading("#0", text="Listado Elementos", anchor=CENTER)
    arbol2.column("col1", width=150, anchor=CENTER)
    arbol2.heading("col1", text="Producto", anchor=CENTER)
    arbol2.column("col2", width=150, anchor=CENTER)
    arbol2.heading("col2", text="Cantidad", anchor=CENTER)
    arbol2.column("col3", width=150, anchor=CENTER)
    arbol2.heading("col3", text="Código:", anchor=CENTER)
    arbol2.column("col4", width=150, anchor=CENTER)
    arbol2.heading("col4", text="Precio", anchor=CENTER)
    arbol2.place(y=440) 




mainloop()